/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rgt.gui;

import java.awt.Container;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import org.rgt.Credential;
import org.rgt.TerminalUtil;

/**
 *
 * @author fabio_uggeri
 */
public class LoginWindow extends javax.swing.JDialog {

   private Credential credential = null;

   /**
    * Creates new form LoginWindow
    */
   private LoginWindow(final Credential credential) {
      initComponents();
      configureComponents();
      if (credential != null && !TerminalUtil.isEmpty(credential.getUsername())) {
         userField.setText(credential.getUsername());
         passwordField.grabFocus();
      }
   }

   public static Credential showWindow(Container parent, Credential credential) {
      final LoginWindow window = new LoginWindow(credential);
      TerminalUtil.centralize(parent, window);
      window.setModal(true);
      window.toFront();
      window.setVisible(true);
      return window.credential;
   }

   private void cancelLogin() {
      this.credential = null;
      processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
   }

   private KeyAdapter createKeyListener() {
      return new KeyAdapter() {
         @Override
         public void keyReleased(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
               cancelLogin();
            } else {
               boolean habilitado = userField.getText().trim().length() > 0
                       && String.valueOf(passwordField.getPassword()).trim().length() > 0;
               buttonLogin.setEnabled(habilitado);
            }
         }
      };
   }

   private FocusListener createFocusListener() {
      return new java.awt.event.FocusAdapter() {
         @Override
         public void focusGained(FocusEvent arg0) {
            ((javax.swing.JTextField) arg0.getComponent()).selectAll();
         }
      };
   }

   private void configureComponents() {
      final KeyAdapter keyListener = createKeyListener();
      final FocusListener focusListener = createFocusListener();
      userField.addKeyListener(keyListener);
      passwordField.addKeyListener(keyListener);
      userField.addFocusListener(focusListener);
      passwordField.addFocusListener(focusListener);
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      buttonLogin = new javax.swing.JButton();
      buttonCancel = new javax.swing.JButton();
      PainelBanner = new javax.swing.JPanel();
      labelLogo = new javax.swing.JLabel();
      userField = new org.rgt.gui.field.IconTextField();
      passwordField = new org.rgt.gui.field.IconPasswordField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      setTitle(bundle.getString("LoginWindow.title")); // NOI18N
      setIconImage(new javax.swing.ImageIcon(getClass().getResource("/credential_32.png")).getImage());

      buttonLogin.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
      buttonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm16.png"))); // NOI18N
      buttonLogin.setText(bundle.getString("LoginWindow.confirm.label")); // NOI18N
      buttonLogin.setEnabled(false);
      buttonLogin.setPreferredSize(new java.awt.Dimension(99, 27));
      buttonLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonLoginActionPerformed(evt);
         }
      });

      buttonCancel.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
      buttonCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel16.png"))); // NOI18N
      buttonCancel.setText(bundle.getString("LoginWindow.cancel.label")); // NOI18N
      buttonCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCancelActionPerformed(evt);
         }
      });

      PainelBanner.setBackground(new java.awt.Color(255, 255, 255));

      labelLogo.setBackground(new java.awt.Color(255, 255, 255));
      labelLogo.setFont(new java.awt.Font("Microsoft YaHei", 1, 36)); // NOI18N
      labelLogo.setForeground(new java.awt.Color(51, 51, 51));
      labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/credential_48.png"))); // NOI18N
      labelLogo.setText(bundle.getString("LoginWindow.banner.text")); // NOI18N
      labelLogo.setToolTipText("");
      labelLogo.setRequestFocusEnabled(false);

      javax.swing.GroupLayout PainelBannerLayout = new javax.swing.GroupLayout(PainelBanner);
      PainelBanner.setLayout(PainelBannerLayout);
      PainelBannerLayout.setHorizontalGroup(
         PainelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(labelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
      );
      PainelBannerLayout.setVerticalGroup(
         PainelBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(PainelBannerLayout.createSequentialGroup()
            .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
      );

      userField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      userField.setHint(bundle.getString("LoginWindow.user.label")); // NOI18N
      userField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user20.png"))); // NOI18N

      passwordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
      passwordField.setHint(bundle.getString("LoginWindow.password.label")); // NOI18N
      passwordField.setIcon(new javax.swing.ImageIcon(getClass().getResource("/password20.png"))); // NOI18N
      passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            passwordFieldKeyPressed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(PainelBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(userField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonCancel, buttonLogin});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(PainelBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(buttonCancel)
               .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
      confirmLogin();
   }//GEN-LAST:event_buttonLoginActionPerformed

   private void confirmLogin() {
      this.credential = new Credential(userField.getText().trim(), String.valueOf(passwordField.getPassword()));
      processWindowEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
   }

   private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
      cancelLogin();
   }//GEN-LAST:event_buttonCancelActionPerformed

   private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER && buttonLogin.isEnabled()) {
         confirmLogin();
      }
   }//GEN-LAST:event_passwordFieldKeyPressed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel PainelBanner;
   private javax.swing.JButton buttonCancel;
   private javax.swing.JButton buttonLogin;
   private javax.swing.JLabel labelLogo;
   private org.rgt.gui.field.IconPasswordField passwordField;
   private org.rgt.gui.field.IconTextField userField;
   // End of variables declaration//GEN-END:variables
}
