/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rgt.gui;

import org.rgt.protocol.admin.files.RemoteFileOperationListener;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.text.DateFormat;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.rgt.SerialExecutor;
import org.rgt.TerminalException;
import org.rgt.TerminalUtil;
import org.rgt.client.RemoteFolder;
import org.rgt.client.RemoteTerminalServer;
import org.rgt.gui.table.DecoratorTableCellRenderer;
import org.rgt.gui.table.EditableTableRowSorter;
import org.rgt.gui.table.FileExtensionDecorator;
import org.rgt.gui.table.FileInfoModel;
import org.rgt.gui.table.ModelRowFilter;
import org.rgt.gui.table.RowComparator;
import org.rgt.gui.table.TableCellRendererDecorator;
import org.rgt.gui.table.TableFilter;
import org.rgt.protocol.admin.files.FileInfo;

/**
 *
 * @author fabio_uggeri
 */
public class RemoteFilesWindow extends javax.swing.JDialog implements ListSelectionListener {

   private static final int FILE_NAME = 0;
   private static final int FILE_SIZE = 1;
   private static final int FILE_CREATION = 2;
   private static final int FILE_MODIFIED = 3;

   private static final DateFormat DATE_FORMAT = DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.MEDIUM);

   private final FileInfoSortComparator fileSortComparator = new FileInfoSortComparator();

   private final List<RemoteFileOperationListener> listeners = new ArrayList<>();

   private final SerialExecutor executor;

   private Instant lastKeyTyped = Instant.now();

   private final StringBuilder currentSearch = new StringBuilder(30);

   private boolean continueRemoteOperation = false;

   private boolean loadingRemoteFiles = false;


   private final RemoteTerminalServer server;

   private final FileMaskRowFilter extensionRowFilter = new FileMaskRowFilter();

   private File lastLocalSelectedFolder = null;

   private String focusGainedText = "";

   public RemoteFilesWindow(java.awt.Frame parent, RemoteTerminalServer server) {
      super(parent, true);
      initComponents();
      this.server = server;
      this.executor = SerialExecutor.newInstance("RemoteFiles: " + server.getId());
      configureComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      filesTable = new javax.swing.JTable();
      jPanel1 = new javax.swing.JPanel();
      jToolBar2 = new javax.swing.JToolBar();
      btnUpload = new javax.swing.JButton();
      btnDownload = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JToolBar.Separator();
      btnRemove = new javax.swing.JButton();
      jToolBar3 = new javax.swing.JToolBar();
      btnClose = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jToolBar1 = new javax.swing.JToolBar();
      btnParentDir = new javax.swing.JButton();
      currentPath = new javax.swing.JTextField();
      btnRefresh = new javax.swing.JButton();
      jToolBar4 = new javax.swing.JToolBar();
      filesFilter = new javax.swing.JTextField();
      jPanel3 = new javax.swing.JPanel();
      totalSelectedItems = new javax.swing.JLabel();
      progressPanel = new javax.swing.JPanel();
      progressBar = new javax.swing.JProgressBar();
      btnCancel = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Remote Files");
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      filesTable.setAutoCreateRowSorter(true);
      filesTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      filesTable.setModel(new FileInfoModel());
      filesTable.setFillsViewportHeight(true);
      filesTable.setName("filesTable"); // NOI18N
      filesTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
      filesTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
      filesTable.setShowGrid(false);
      filesTable.getTableHeader().setReorderingAllowed(false);
      filesTable.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            filesTableFocusGained(evt);
         }
      });
      filesTable.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            filesTableMouseClicked(evt);
         }
      });
      filesTable.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            filesTableKeyPressed(evt);
         }
      });
      jScrollPane1.setViewportView(filesTable);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upload2.png"))); // NOI18N
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      btnUpload.setToolTipText(bundle.getString("RemoteFilesWindow.btnUpload.hint")); // NOI18N
      btnUpload.setFocusable(false);
      btnUpload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnUpload.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnUpload.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnUploadActionPerformed(evt);
         }
      });
      jToolBar2.add(btnUpload);

      btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/download2.png"))); // NOI18N
      btnDownload.setToolTipText(bundle.getString("RemoteFilesWindow.btnDownload.hint")); // NOI18N
      btnDownload.setEnabled(false);
      btnDownload.setFocusable(false);
      btnDownload.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnDownload.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnDownload.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnDownloadActionPerformed(evt);
         }
      });
      jToolBar2.add(btnDownload);
      jToolBar2.add(jSeparator1);

      btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trash2_32.png"))); // NOI18N
      btnRemove.setToolTipText(bundle.getString("RemoteFilesWindow.btnRemove.hint")); // NOI18N
      btnRemove.setEnabled(false);
      btnRemove.setFocusable(false);
      btnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRemove.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoveActionPerformed(evt);
         }
      });
      jToolBar2.add(btnRemove);

      jToolBar3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar3.setRollover(true);

      btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      btnClose.setToolTipText(bundle.getString("RemoteFilesWindow.btnClose.toolTipText")); // NOI18N
      btnClose.setFocusable(false);
      btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });
      jToolBar3.add(btnClose);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
               .addGap(0, 635, Short.MAX_VALUE)
               .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 4, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      btnParentDir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/folder_up_16_2.png"))); // NOI18N
      btnParentDir.setToolTipText(bundle.getString("RemoteFilesWindow.btnUp.toolTipText")); // NOI18N
      btnParentDir.setFocusable(false);
      btnParentDir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnParentDir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnParentDir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnParentDirActionPerformed(evt);
         }
      });
      jToolBar1.add(btnParentDir);

      currentPath.setToolTipText(bundle.getString("RemoteFilesWindow.remote_path.hint")); // NOI18N
      currentPath.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusGained(java.awt.event.FocusEvent evt) {
            currentPathFocusGained(evt);
         }
         public void focusLost(java.awt.event.FocusEvent evt) {
            currentPathFocusLost(evt);
         }
      });
      currentPath.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            currentPathKeyPressed(evt);
         }
      });
      jToolBar1.add(currentPath);

      btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh2_16.png"))); // NOI18N
      btnRefresh.setFocusable(false);
      btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRefresh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
         }
      });
      jToolBar1.add(btnRefresh);

      jToolBar4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar4.setRollover(true);

      filesFilter.setToolTipText(bundle.getString("RemoteFilesWindow.filter.hint")); // NOI18N
      filesFilter.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            filesFilterFocusLost(evt);
         }
      });
      filesFilter.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            filesFilterKeyPressed(evt);
         }
      });
      jToolBar4.add(filesFilter);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
               .addGap(161, 161, 161)))
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE))
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      totalSelectedItems.setText("0 selected items 0 KB");
      totalSelectedItems.setName(""); // NOI18N

      btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel16.png"))); // NOI18N
      btnCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
      progressPanel.setLayout(progressPanelLayout);
      progressPanelLayout.setHorizontalGroup(
         progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, progressPanelLayout.createSequentialGroup()
            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(2, 2, 2)
            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
      );
      progressPanelLayout.setVerticalGroup(
         progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(totalSelectedItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
            .addComponent(totalSelectedItems, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(3, 3, 3)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
            .addGap(0, 0, 0)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   public boolean addListener(RemoteFileOperationListener listener) {
      return listeners.add(listener);
   }

   public boolean removeListener(RemoteFileOperationListener listener) {
      return listeners.remove(listener);
   }

   public void clearListeners() {
      listeners.clear();
   }

   private void filterByMask(final String mask) {
      extensionRowFilter.clearFilters();
      extensionRowFilter.addFilter(mask.trim());
      filesModel().fireTableDataChanged();
   }


   private void btnParentDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParentDirActionPerformed
      final File currentFilePath = new File(server.getLastViewedRemotePath());
      final File parentFilePath = currentFilePath.getParentFile();
      if (parentFilePath != null) {
         executor.execute(() -> {
            loadFiles(parentFilePath.getPath(), false);
            filesTable.requestFocus();
         });
      }
   }//GEN-LAST:event_btnParentDirActionPerformed

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      exit();
   }//GEN-LAST:event_btnCloseActionPerformed

   private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
      final JFileChooser fileChooser;
      if (lastLocalSelectedFolder == null) {
         lastLocalSelectedFolder = new File(System.getProperty("user.home"));
      }
      fileChooser = new JFileChooser(lastLocalSelectedFolder);
      fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
      fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
      fileChooser.setMultiSelectionEnabled(true);
      if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
         final File[] files = fileChooser.getSelectedFiles();
         if (files.length > 0) {
            lastLocalSelectedFolder = files[0].getParentFile();
            executor.execute(() -> uploadFiles(files));
         }
      }
   }//GEN-LAST:event_btnUploadActionPerformed

   private int confirmReplaceLocalFiles(final File localFolder, final FileInfo[] filesToDownload) {
      final List<File> foundFiles = new ArrayList<>();
      for (final FileInfo file : filesToDownload) {
         final File localFile = new File(localFolder, file.getName());
         if (localFile.exists()) {
            foundFiles.add(localFile);
         }
      }
      if (!foundFiles.isEmpty()) {
         return JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("RemoteFilesWindow.local_replace_confirmation.msg",
                 TerminalUtil.toString(foundFiles, "\n")),
                 TerminalUtil.getMessage("RemoteFilesWindow.local_replace_confirmation.title"),
                 JOptionPane.YES_NO_CANCEL_OPTION);
      }
      return JOptionPane.YES_OPTION;
   }

   private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
      final JFileChooser fileChooser;
      if (lastLocalSelectedFolder == null) {
         lastLocalSelectedFolder = new File(System.getProperty("user.home"));
      }
      fileChooser = new JFileChooser(lastLocalSelectedFolder);
      fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
      fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
      if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
         final File selectedFile = fileChooser.getSelectedFile();
         if (selectedFile != null && selectedFile.isDirectory()) {
            final FileInfo[] filesToDownload = selectedFiles();
            final int confirm;
            lastLocalSelectedFolder = fileChooser.getSelectedFile();
            confirm = confirmReplaceLocalFiles(fileChooser.getSelectedFile(), filesToDownload);
            if (confirm == JOptionPane.YES_OPTION || confirm == JOptionPane.NO_OPTION) {
               executor.execute(() -> downloadSelectedFiles(fileChooser.getSelectedFile(),
                       filesToDownload, confirm == JOptionPane.YES_OPTION));
            }
         } else {
            JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("RemoteFilesWindow.invalid_local_dir.msg"),
                    TerminalUtil.getMessage("RemoteFilesWindow.invalid_local_dir.title"), JOptionPane.ERROR_MESSAGE);
         }
      }
   }//GEN-LAST:event_btnDownloadActionPerformed

   private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
      removeRemoteFiles();
   }//GEN-LAST:event_btnRemoveActionPerformed

   private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      executor.execute(() -> {
         loadFiles(server.getLastViewedRemotePath(), false);
         filesTable.requestFocus();
      });
   }//GEN-LAST:event_formWindowOpened

   private void filesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filesTableMouseClicked
      final int row = filesTable.rowAtPoint(evt.getPoint());
      if (evt.getClickCount() == 2 && row >= 0) {
         final int modelRow = filesTable.convertRowIndexToModel(row);
         final FileInfo file = modelRow >= 0 ? filesModel().fileInfoAt(modelRow) : null;
         if (file != null && file.isDirectory()) {
            executor.execute(() -> loadFiles(new File(server.getLastViewedRemotePath(), file.getName()).getAbsolutePath(), false));
         }
      }

   }//GEN-LAST:event_filesTableMouseClicked

   private boolean isValidFilenameChar(final char c) {
      switch (c) {
         case '\'':
         case '_':
         case '-':
         case '+':
         case '&':
         case ' ':
         case '.':
         case '(':
         case ')':
         case '{':
         case '}':
         case '[':
         case ']':
         case '$':
         case '%':
         case '#':
         case '@':
         case '!':
            return true;
         default:
            return (c >= 'A' && c <= 'Z')
                    || (c >= 'a' && c <= 'z')
                    || (c >= '0' && c <= '9');
      }
   }

   private void searchNextFile() {
      FileInfoModel model = filesModel();
      final String lowerSearch = currentSearch.toString().toLowerCase();
      for (int i = filesTable.getSelectedRow(); i < filesTable.getRowCount(); i++) {
         final int modelRow = filesTable.convertRowIndexToModel(i);
         final FileInfo file = modelRow >= 0 ? model.fileInfoAt(modelRow) : null;
         if (file != null && file.getName().toLowerCase().startsWith(lowerSearch)) {
            selectRow(i);
            return;
         }
      }
   }

   private void selectFirstRow(java.awt.event.KeyEvent evt) {
      currentSearch.setLength(0);
      if (filesTable.getRowCount() > 0) {
         if (evt.isShiftDown()) {
            selectRows(0, filesTable.getSelectedRow(), 0);
         } else {
            selectRow(0);
         }
         evt.consume();
      }
   }

   private void selectLastRow(java.awt.event.KeyEvent evt) {
      currentSearch.setLength(0);
      if (filesTable.getRowCount() > 0) {
         if (evt.isShiftDown()) {
            selectRows(filesTable.getSelectedRow(), filesTable.getRowCount() - 1, filesTable.getRowCount() - 1);
         } else {
            selectRow(filesTable.getRowCount() - 1);
         }
         evt.consume();
      }
   }

   private void selectRow(int row) {
      filesTable.setRowSelectionInterval(row, row);
      filesTable.scrollRectToVisible(filesTable.getCellRect(row, 0, false));
   }

   private void selectRows(int firstRow, int lastRow, int visibleRow) {
      filesTable.setRowSelectionInterval(firstRow, lastRow);
      filesTable.scrollRectToVisible(filesTable.getCellRect(visibleRow, 0, false));
   }

   private void filesTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filesTableKeyPressed
      switch (evt.getKeyCode()) {
         case KeyEvent.VK_ENTER:
            enterSelectedFolder();
            break;
         case KeyEvent.VK_DELETE:
            removeRemoteFiles();
            break;
         case KeyEvent.VK_HOME:
            selectFirstRow(evt);
            break;
         case KeyEvent.VK_END:
            selectLastRow(evt);
            break;
         default:
            if (isValidFilenameChar(evt.getKeyChar())) {
               if (Duration.between(lastKeyTyped, Instant.now()).toSeconds() > 2) {
                  currentSearch.setLength(0);
               }
               currentSearch.append(evt.getKeyChar());
               lastKeyTyped = Instant.now();
               searchNextFile();
            } else {
               currentSearch.setLength(0);
            }
            break;
      }
   }//GEN-LAST:event_filesTableKeyPressed

   private void removeRemoteFiles() {
      if (btnRemove.isEnabled()
              && filesTable.getSelectedRowCount() > 0
              && JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("RemoteFilesWindow.remove_confirmation.msg"),
                      TerminalUtil.getMessage("RemoteFilesWindow.remove_confirmation.title"),
                      JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
         executor.execute(() -> removeSelectedFiles());
      }
   }

   private void enterSelectedFolder() {
      if (filesTable.getSelectedRowCount() == 1) {
         final int modelRow = filesTable.convertRowIndexToModel(filesTable.getSelectedRow());
         final FileInfo file = modelRow >= 0 ? filesModel().fileInfoAt(modelRow) : null;
         if (file != null && file.isDirectory()) {
            executor.execute(() -> loadFiles(new File(server.getLastViewedRemotePath(), file.getName()).getAbsolutePath(), false));
         }
      }
   }

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      executor.execute(() -> {
         loadFiles(server.getLastViewedRemotePath(), true);
         filesTable.requestFocus();
      } );
   }//GEN-LAST:event_btnRefreshActionPerformed

   private void filesFilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filesFilterKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         filesTable.requestFocus();
      }
   }//GEN-LAST:event_filesFilterKeyPressed

   private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
      continueRemoteOperation = false;
   }//GEN-LAST:event_btnCancelActionPerformed

   private void currentPathKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currentPathKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         filesTable.requestFocus();
      }
   }//GEN-LAST:event_currentPathKeyPressed

   private void currentPathFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPathFocusGained
      focusGainedText = currentPath.getText();
      currentPath.selectAll();
   }//GEN-LAST:event_currentPathFocusGained

   private void currentPathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_currentPathFocusLost
      if (! TerminalUtil.equals(focusGainedText, currentPath.getText())) {
         focusGainedText = currentPath.getText();
         executor.execute(() -> loadFiles(currentPath.getText(), true));
      }
   }//GEN-LAST:event_currentPathFocusLost

   private void filesTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filesTableFocusGained
      if (filesTable.getSelectedRow() == -1 && filesTable.getRowCount() > 0) {
         filesTable.setRowSelectionInterval(0, 0);
      }
   }//GEN-LAST:event_filesTableFocusGained

   private void filesFilterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_filesFilterFocusLost
      filterByMask(filesFilter.getText());
   }//GEN-LAST:event_filesFilterFocusLost

   private void exit() throws HeadlessException {
      executor.stop(true);
      setVisible(false);
   }

   private void configureComponents() {
      setTitle(TerminalUtil.getMessage("RemoteFilesWindow.title", server.getId() + " - " + server.getRemoteServerAddress()));
      TerminalUtil.centralize(getParent(), this);
      progressPanel.setVisible(false);
      configureFilesTable();
   }

   private void configureFilesTable() {
      final TableColumnModel colModel = filesTable.getColumnModel();
      final DecoratorTableCellRenderer fileSizeRenderer;
      final DecoratorTableCellRenderer dateTimeRenderer;
      final EditableTableRowSorter rowSorter;

      fileSizeRenderer = new DecoratorTableCellRenderer((TableCellRendererDecorator<FileInfoModel, JLabel>) (table, model, label, row, col, sel, focus) -> {
         final int modelRow = filesTable.convertRowIndexToModel(row);
         final FileInfo file = modelRow >= 0 ? model.fileInfoAt(modelRow) : null;
         if (file == null || file.isDirectory()) {
            label.setText("");
         } else if (file.getLength() == 0L) {
            label.setText("0 KB");
         } else if (file.getLength() < 1024L) {
            label.setText("1 KB");
         } else {
            label.setText(((long) (file.getLength() / 1024)) + " KB");
         }
      });

      dateTimeRenderer = new DecoratorTableCellRenderer((TableCellRendererDecorator<FileInfoModel, JLabel>) (table, model, label, row, col, sel, focus) -> {
         final FileInfo file = model.fileInfoAt(filesTable.convertRowIndexToModel(row));
         final Date dateTime;
         if (file == null) {
            return;
         }
         switch (col) {
            case FILE_CREATION:
               dateTime = file.getCreationTime();
               break;
            case FILE_MODIFIED:
               dateTime = file.getLastModificationTime();
               break;
            default:
               return;
         }
         label.setText(DATE_FORMAT.format(dateTime));
      });

      filesTable.setModel(new FileInfoModel());
      filesTable.getTableHeader().setToolTipText(TerminalUtil.getMessage("RemoteFilesWindow.files.header.tooltip"));
      colModel.getColumn(FILE_NAME).setResizable(true);
      colModel.getColumn(FILE_NAME).setCellRenderer(new DecoratorTableCellRenderer(new FileExtensionDecorator()));
      colModel.getColumn(FILE_NAME).setPreferredWidth(250);
      colModel.getColumn(FILE_SIZE).setResizable(true);
      colModel.getColumn(FILE_SIZE).setPreferredWidth(70);
      colModel.getColumn(FILE_SIZE).setCellRenderer(fileSizeRenderer);
      colModel.getColumn(FILE_CREATION).setResizable(true);
      colModel.getColumn(FILE_CREATION).setPreferredWidth(100);
      colModel.getColumn(FILE_CREATION).setCellRenderer(dateTimeRenderer);
      colModel.getColumn(FILE_MODIFIED).setResizable(true);
      colModel.getColumn(FILE_MODIFIED).setPreferredWidth(100);
      colModel.getColumn(FILE_MODIFIED).setCellRenderer(dateTimeRenderer);
      filesTable.setColumnSelectionAllowed(false);
      filesTable.setRowSelectionAllowed(true);
      filesTable.getSelectionModel().addListSelectionListener(this);
      TableFilter.forTable(filesTable).apply().repaint();
      rowSorter = (EditableTableRowSorter) filesTable.getRowSorter();
      rowSorter.setRowComparator(fileSortComparator);
      rowSorter.setRowFilter(new MultiRowFilter<>(rowSorter.getRowFilter(), extensionRowFilter));
   }

   private void sortFilesModel(final FileInfoModel filesModel) {
      final List<RowSorter.SortKey> sortKeys = ((EditableTableRowSorter) filesTable.getRowSorter()).getSortKeys();
      if (sortKeys.isEmpty()) {
         fileSortComparator.sort(filesModel, 0, SortOrder.ASCENDING);
      } else {
         fileSortComparator.sort(filesModel, sortKeys);
      }
   }

   private void updateModel(final RemoteFolder remoteFolder) {
      final FileInfoModel filesModel = filesModel();
      filesModel.clearFiles(false);
      filesModel.addFiles(remoteFolder.files(), false);
      sortFilesModel(filesModel);
      filesModel.fireTableDataChanged();
      if (filesModel.getRowCount() > 0) {
         filesTable.setRowSelectionInterval(0, 0);
      }
   }

   private void loadFiles(final String path, boolean notify) {
      try {
         final RemoteFolder remoteFolder;
         loadingRemoteFiles = true;
         progressBar.setIndeterminate(true);
         progressPanel.setVisible(true);
         remoteFolder = server.listRemoteFiles(path);
         server.setLastViewedRemotePath(remoteFolder.pathName());
         currentPath.setText(server.getLastViewedRemotePath());
         if (notify) {
            notifyListRemoteFiles(remoteFolder.files());
         }
         java.awt.EventQueue.invokeLater(() -> updateModel(remoteFolder));
      } catch (TerminalException ex) {
         JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                 TerminalUtil.getMessage("RemoteFilesWindow.error_loading.msg"), JOptionPane.ERROR_MESSAGE);
      } finally {
         progressPanel.setVisible(false);
         progressBar.setIndeterminate(false);
         loadingRemoteFiles = false;
      }
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancel;
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnDownload;
   private javax.swing.JButton btnParentDir;
   private javax.swing.JButton btnRefresh;
   private javax.swing.JButton btnRemove;
   private javax.swing.JButton btnUpload;
   private javax.swing.JTextField currentPath;
   private javax.swing.JTextField filesFilter;
   private javax.swing.JTable filesTable;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JToolBar.Separator jSeparator1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private javax.swing.JToolBar jToolBar3;
   private javax.swing.JToolBar jToolBar4;
   private javax.swing.JProgressBar progressBar;
   private javax.swing.JPanel progressPanel;
   private javax.swing.JLabel totalSelectedItems;
   // End of variables declaration//GEN-END:variables

   private FileInfoModel filesModel() {
      return (FileInfoModel) filesTable.getModel();
   }

   private int[] modelSelectedRows() {
      final int[] selectedRows = filesTable.getSelectedRows();
      for (int i = 0; i < selectedRows.length; i++) {
         selectedRows[i] = filesTable.convertRowIndexToModel(selectedRows[i]);
      }
      return selectedRows;
   }

   private FileInfo[] selectedFiles() {
      final FileInfoModel model = filesModel();
      final int[] selectedRows = filesTable.getSelectedRows();
      final FileInfo[] filesSelected = new FileInfo[selectedRows.length];
      for (int i = 0; i < selectedRows.length; i++) {
         filesSelected[i] = model.fileInfoAt(filesTable.convertRowIndexToModel(selectedRows[i]));
      }
      return filesSelected;
   }

   private void notifyListRemoteFiles(final List<FileInfo> files) {
      listeners.forEach(l -> l.listFiles(server, server.getLastViewedRemotePath(), files));
   }

   private void notifyRemoveRemoteFile(final FileInfo file) {
      listeners.forEach(l -> l.removeFile(server, file));
   }

   private void notifyUploadRemoteFile(final FileInfo source, final FileInfo target) {
      listeners.forEach(l -> l.uploadFile(server, source, target));
   }

   private void notifyDownloadRemoteFile(final FileInfo source, final FileInfo target) {
      listeners.forEach(l -> l.downloadFile(server, source, target));
   }

   private void notification(final String error) {
      listeners.forEach(l -> l.notification(error));
   }

   private int totalSize(final File[] files) {
      int totalSize = 0;
      for (File file : files) {
         if (file.isFile()) {
            totalSize += file.length();
         }
      }
      return totalSize;
   }

   private void uploadFiles(final File[] filesToUpload) {
      final FileInfoModel model = filesModel();
      int success = 0;
      try {
         int totalToUpload = totalSize(filesToUpload);
         progressBar.setMaximum(totalToUpload);
         progressBar.setValue(0);
         progressPanel.setVisible(true);
         continueRemoteOperation = true;
         for (File localFile : filesToUpload) {
            final File remoteFile;
            if (!continueRemoteOperation) {
               notification("Operation canceled by user");
               break;
            }
            remoteFile = new File(server.getLastViewedRemotePath(), localFile.getName());
            try {
               if (server.uploadFile(localFile, server.getLastViewedRemotePath(), false,
                       (int chunk) -> {
                          progressBar.setValue(progressBar.getValue() + chunk);
                          return continueRemoteOperation;
                       })) {
                  ++success;
                  notifyUploadRemoteFile(new FileInfo(remoteFile.getPath()), new FileInfo(localFile));
                  model.addFile(new FileInfo(localFile));
               }
            } catch (TerminalException ex) {
               notification(TerminalUtil.getMessage("RemoteFilesWindow.upload_file_error", remoteFile, localFile, server, ex.getMessage()));
            }
         }
      } finally {
         notification(TerminalUtil.getMessage("RemoteFilesWindow.operation_completed.msg", success, filesToUpload.length - success));
         progressPanel.setVisible(false);
      }
   }

   private int totalSize(final FileInfo[] files) {
      int totalSize = 0;
      for (FileInfo file : files) {
         if (file.isFile()) {
            totalSize += file.getLength();
         }
      }
      return totalSize;
   }

   private void downloadSelectedFiles(final File localFolder, final FileInfo[] filesToDownload, final boolean overwriteLocal) {
      int success = 0;
      try {
         final int totalToDownload = totalSize(filesToDownload);
         progressBar.setMaximum(totalToDownload);
         progressBar.setValue(0);
         progressPanel.setVisible(true);
         continueRemoteOperation = true;
         for (FileInfo file : filesToDownload) {
            final File remoteFile;
            final File localFile;
            if (!continueRemoteOperation) {
               notification("Operation canceled by user");
               break;
            }

            remoteFile = new File(server.getLastViewedRemotePath(), file.getName());
            localFile = new File(localFolder, file.getName());
            try {
               if (server.downloadFile(remoteFile.getPath(), localFile, overwriteLocal,
                       (int chunk) -> {
                          progressBar.setValue(progressBar.getValue() + chunk);
                          return continueRemoteOperation;
                       })) {
                  ++success;
                  notifyDownloadRemoteFile(new FileInfo(remoteFile.getPath()), new FileInfo(localFile.getParent()));
               }
            } catch (TerminalException ex) {
               notification(TerminalUtil.getMessage("RemoteFilesWindow.download_file_error", remoteFile, localFile, server, ex.getMessage()));
            }
         }
      } finally {
         notification(TerminalUtil.getMessage("RemoteFilesWindow.operation_completed.msg", success, filesToDownload.length - success));
         progressPanel.setVisible(false);
      }
   }

   private void removeSelectedFiles() {
      final FileInfo[] filesToRemove = selectedFiles();
      final FileInfoModel model = filesModel();
      int success = 0;
      try {
         progressBar.setMaximum(filesToRemove.length);
         progressBar.setValue(0);
         progressPanel.setVisible(true);
         continueRemoteOperation = true;
         for (FileInfo file : filesToRemove) {
            final File remoteFile;
            if (!continueRemoteOperation) {
               notification("Operation canceled by user");
               break;
            }
            remoteFile = new File(server.getLastViewedRemotePath(), file.getName());
            try {
               if (server.removeFile(server.getLastViewedRemotePath(), file.getName())) {
                  notifyRemoveRemoteFile(new FileInfo(remoteFile.getPath()));
                  model.removeFile(file);
                  ++success;
               }
            } catch (TerminalException ex) {
               notification(TerminalUtil.getMessage("RemoteFilesWindow.remove_file_error", remoteFile, server, ex.getMessage()));
            } finally {
               progressBar.setValue(progressBar.getValue() + 1);
            }
         }
      } finally {
         notification(TerminalUtil.getMessage("RemoteFilesWindow.operation_completed.msg", success, filesToRemove.length - success));
         progressPanel.setVisible(false);
      }
   }

   @Override
   public void valueChanged(ListSelectionEvent e) {
      if (!loadingRemoteFiles && !e.getValueIsAdjusting()) {
         verifySelection();
      }
   }

   private void verifySelection() {
      final FileInfoModel model = filesModel();
      int[] selectedRows = modelSelectedRows();
      int selectedFiles = 0;
      int selectedDirs = 0;
      long totalSize = 0;
      for (int row : selectedRows) {
         final FileInfo file = model.fileInfoAt(row);
         if (file.isFile()) {
            if (file.getLength() < 1024L) {
               ++totalSize;
            } else {
               totalSize += (long) (file.getLength() / 1024);
            }
            ++selectedFiles;
         } else {
            ++selectedDirs;
         }
      }
      btnRemove.setEnabled(selectedFiles > 0 && selectedDirs == 0);
      btnDownload.setEnabled(selectedFiles > 0 && selectedDirs == 0);
      totalSelectedItems.setText(TerminalUtil.getMessage("RemoteFilesWindow.selected_files_status", selectedFiles, totalSize + " KB"));
   }

   private class MultiRowFilter<T extends TableModel> implements ModelRowFilter<T> {

      private final List<ModelRowFilter<T>> filters = new ArrayList<>();

      public MultiRowFilter(ModelRowFilter<T>... filters) {
         this.filters.addAll(Arrays.asList(filters));
      }

      @Override
      public boolean include(T model, int row) {
         for (ModelRowFilter<T> f : filters) {
            if (!f.include(model, row)) {
               return false;
            }
         }
         return true;
      }

      @Override
      public boolean isFiltered(int column) {
         for (ModelRowFilter<T> f : filters) {
            if (f.isFiltered(column)) {
               return true;
            }
         }
         return false;
      }

   }

   private class FileMaskRowFilter implements ModelRowFilter<FileInfoModel> {

      private final List<Pattern> maskPatterns = new ArrayList<>();

      public FileMaskRowFilter(final String... filters) {
         for (final String f : filters) {
            final Pattern p = createFilterPattern(f);
            if (p != null) {
               maskPatterns.add(p);
            }
         }
      }

      @Override
      public boolean include(FileInfoModel model, int row) {
         final FileInfo file;
         if (maskPatterns.isEmpty()) {
            return true;
         }
         file = model.fileInfoAt(row);
         if (file == null) {
            return false;
         }
         if (file.isDirectory()) {
            return true;
         }
         for (Pattern p : maskPatterns) {
            if (p.matcher(file.getName()).matches()) {
               return true;
            }
         }
         return false;
      }

      @Override
      public boolean isFiltered(int column) {
         return !maskPatterns.isEmpty() && column == FILE_NAME;
      }

      public boolean addFilter(final String filter) {
         final Pattern p = createFilterPattern(filter);
         if (p != null) {
            return maskPatterns.add(p);
         }
         return false;
      }

      public void clearFilters() {
         maskPatterns.clear();
      }

      private Pattern createFilterPattern(String filter) {
         if (filter.indexOf('*') >= 0 || filter.indexOf('?') >= 0) {
            final StringBuilder sb = new StringBuilder(filter.length() + 12);
            for (int i = 0; i < filter.length(); i++) {
               final char c = filter.charAt(i);
               switch (c) {
                  case '*':
                     sb.append(".*");
                     break;
                  case '?':
                     sb.append('.');
                     break;
                  case '.':
                     sb.append('\\').append('.');
                     break;
                  default:
                     sb.append(c);
                     break;
               }
            }
            return Pattern.compile(sb.toString());
         }
         return null;
      }

   }

   private class FileInfoSortComparator implements RowComparator<FileInfoModel> {

      public void sort(final FileInfoModel model, final List<RowSorter.SortKey> sortKeys) {
         model.sort((FileInfo file1, FileInfo file2) -> {
            for (RowSorter.SortKey sortKey : sortKeys) {
               final int result = compareFiles(sortKey.getColumn(), file1, file2);
               if (result != 0) {
                  return result * (sortKey.getSortOrder() == SortOrder.ASCENDING ? 1 : -1);
               }
            }
            return 0;
         });
      }

      public void sort(final FileInfoModel model, final int column, final SortOrder order) {
         model.sort((FileInfo f1, FileInfo f2) -> compareFiles(column, f1, f2) * (order == SortOrder.ASCENDING ? 1 : -1));
      }

      @Override
      public int compare(final FileInfoModel model, RowSorter.SortKey sortKey, int firstRow, int secondRow) {
         final FileInfo file1 = model.fileInfoAt(firstRow);
         final FileInfo file2 = model.fileInfoAt(secondRow);
         return compareFiles(sortKey.getColumn(), file1, file2) * (sortKey.getSortOrder() == SortOrder.ASCENDING ? 1 : -1);
      }

      private int compareFiles(int column, FileInfo file1, FileInfo file2) {
         int comp;
         if (file1.getFileType() == file2.getFileType()) {
            switch (column) {
               case 1:
                  comp = Long.signum(file1.getLength() - file2.getLength());
                  break;
               case 2:
                  comp  = file1.getCreationTime().compareTo(file2.getCreationTime());
                  break;
               case 3:
                  comp  = file1.getLastModificationTime().compareTo(file2.getLastModificationTime());
                  break;
               default:
                  comp = file1.getName().compareToIgnoreCase(file2.getName());
                  break;
            }
         } else if (file1.isDirectory()) {
            comp = -1;
         } else {
            comp = 1;
         }
         return comp;
      }

   }
}
