/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rgt.gui;

import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author fabio_uggeri
 */
public class RemoteServerDetails extends javax.swing.JDialog {

   private static final long serialVersionUID = 1017944930488774540L;

   private static final Logger LOG = LoggerFactory.getLogger(RemoteServerDetails.class);

   private boolean confirm = false;

   /**
    * Creates new form RemoteServerDetails
    * @param parent
    * @param modal
    */
   public RemoteServerDetails(java.awt.Frame parent, boolean modal) {
      super(parent, modal);
      Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
      initComponents();
      setLocation((tela.width - getSize().width) / 2, (tela.height - getSize().height) / 2);
      configureComponents();
   }

   private void configureComponents() {
      ((JSpinner.DefaultEditor) port.getEditor()).getTextField().addKeyListener(new java.awt.event.KeyAdapter() {
         @Override
         public void keyPressed(java.awt.event.KeyEvent evt) {
            RemoteServerDetails.this.keyPressed(evt);
         }
      });
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      idLabel = new javax.swing.JLabel();
      addrLabel = new javax.swing.JLabel();
      portLabel = new javax.swing.JLabel();
      id = new javax.swing.JTextField();
      address = new javax.swing.JTextField();
      port = new javax.swing.JSpinner();
      btnClose = new javax.swing.JButton();
      btnConfirm = new javax.swing.JButton();

      setTitle("Server Details");

      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      idLabel.setText(bundle.getString("AddServerDialog.id.label")); // NOI18N

      addrLabel.setText(bundle.getString("AddServerDialog.addr.label")); // NOI18N

      portLabel.setText(bundle.getString("AddServerDialog.port.label")); // NOI18N

      id.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            RemoteServerDetails.this.keyPressed(evt);
         }
      });

      address.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            RemoteServerDetails.this.keyPressed(evt);
         }
      });

      port.setModel(new javax.swing.SpinnerNumberModel(7656, 1, 65535, 1));

      btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel16.png"))); // NOI18N
      btnClose.setText(bundle.getString("AddServerDialog.btnCancel.label")); // NOI18N
      btnClose.setFocusable(false);
      btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });

      btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/confirm16.png"))); // NOI18N
      btnConfirm.setText(bundle.getString("AddServerDialog.btnConfirm.label")); // NOI18N
      btnConfirm.setFocusable(false);
      btnConfirm.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
      btnConfirm.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConfirmActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(addrLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(portLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(idLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(address)
                     .addComponent(port, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                     .addComponent(id)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addComponent(btnConfirm)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(btnClose)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(idLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(addrLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(portLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(btnConfirm, javax.swing.GroupLayout.Alignment.TRAILING))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      closeWithCancelation();
   }//GEN-LAST:event_btnCloseActionPerformed

   private void closeWithCancelation() {
      setVisible(false);
      confirm = false;
   }

   public boolean isValidAddress() {
      try {
         return address.getText().trim().isEmpty() || InetAddress.getByName(address.getText().trim()) != null;
      } catch (UnknownHostException ex) {
         LOG.warn("Invalid address informed.", ex);
      }
      return false;
   }

   private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
      closeWithConfirmation();
   }//GEN-LAST:event_btnConfirmActionPerformed

   private boolean closeWithConfirmation() throws HeadlessException {
      if (id.getText().trim().isEmpty()) {
         JOptionPane.showMessageDialog(this, "Server ID must be informed", "Invalid ID", JOptionPane.ERROR_MESSAGE);
         return false;
      }
      if (!isValidAddress()) {
         JOptionPane.showMessageDialog(this, "Inform a valid host address.", "Invalid host adress", JOptionPane.ERROR_MESSAGE);
         return false;
      }
      try {
         port.commitEdit();
      } catch (ParseException ex) {
         JOptionPane.showMessageDialog(this, "Invalid port number", "Invalid port", JOptionPane.ERROR_MESSAGE);
         return false;
      }
      setVisible(false);
      confirm = true;
      return true;
   }

   private void keyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
         closeWithConfirmation();
      } else if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
         closeWithCancelation();
      }
   }//GEN-LAST:event_keyPressed

   public boolean isConfirm() {
      return confirm;
   }

   public String getId() {
      return id.getText().trim();
   }

   public String getAddress() {
      return address.getText().trim();
   }

   public int getPort() {
      return (Integer) port.getValue();
   }

   public void setId(String id) {
      this.id.setText(id.trim());
   }

   public void setAddress(String address) {
      this.address.setText(address.trim());
   }

   public void setPort(int port) {
      this.port.setValue(port);
   }

   public void disableIdField() {
      id.setEnabled(false);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel addrLabel;
   private javax.swing.JTextField address;
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnConfirm;
   private javax.swing.JTextField id;
   private javax.swing.JLabel idLabel;
   private javax.swing.JSpinner port;
   private javax.swing.JLabel portLabel;
   // End of variables declaration//GEN-END:variables
}
