/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.rgt.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableColumnModelEvent;
import javax.swing.event.TableColumnModelListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.rgt.Notifier;
import org.rgt.RGTLogLevel;
import org.rgt.TerminalException;
import org.rgt.TerminalUtil;
import org.rgt.client.RemoteTerminalServer;
import org.rgt.gui.table.ConfigTableModel;
import org.rgt.options.TerminalOption;
import org.rgt.gui.ConfigOption.OptionType;
import org.rgt.gui.editor.ComboCellEditor;
import org.rgt.gui.editor.CustomCellEditor;
import org.rgt.gui.editor.DefaultCellKeyListener;
import org.rgt.gui.editor.IntegerCellEditor;
import org.rgt.gui.editor.TextCellEditor;
import org.rgt.gui.editor.ValidateDuplicatedKeyListener;
import org.rgt.gui.table.DecoratorTableCellRenderer;
import org.rgt.gui.table.ModifiedCellDecorator;
import org.rgt.gui.table.ValueDiffDecorator;

/**
 *
 * @author fabio_uggeri
 */
public class ServerConfigurationsWindow
        extends javax.swing.JDialog implements TableColumnModelListener, ListSelectionListener {

   private static final Color DIFF_CELL_BACKGROUND = new Color(255, 255, 230);

   private static final int[] COMBO_KEYS = new int[]{KeyEvent.VK_ENTER, KeyEvent.VK_ESCAPE,
      KeyEvent.VK_LEFT, KeyEvent.VK_RIGHT, KeyEvent.VK_TAB, KeyEvent.VK_SPACE};

   private static final int OPTION_NAME = 0;

   private final List<ConfigOption> options = new ArrayList<>();

   private final List<RemoteTerminalServer> servers;

   private final List<TableCellEditor> editors = new ArrayList<>();

   private final Notifier notifier;

   /**
    * Creates new form ServerConfigurationsWindow
    *
    * @param parent
    * @param servers
    * @param notifier
    */
   public ServerConfigurationsWindow(java.awt.Frame parent, List<RemoteTerminalServer> servers, Notifier notifier) {
      super(parent, true);
      this.servers = servers;
      this.notifier = notifier;
      initComponents();
      configureComponents();
   }

   private void configureComponents() {
      setTitle(TerminalUtil.getMessage("ServerConfigWindow.title"));
      TerminalUtil.centralize(null, this);
      configureConfigTable();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jToolBar1 = new javax.swing.JToolBar();
      BtnClose = new javax.swing.JButton();
      jToolBar2 = new javax.swing.JToolBar();
      btnSave = new javax.swing.JButton();
      btnApply = new javax.swing.JButton();
      jSeparator2 = new javax.swing.JToolBar.Separator();
      btnAdd = new javax.swing.JButton();
      btnRemove = new javax.swing.JButton();
      copyButtonsSep = new javax.swing.JToolBar.Separator();
      btnCopyLeft = new javax.swing.JButton();
      btnCopyToAll = new javax.swing.JButton();
      btnCopyRight = new javax.swing.JButton();
      jScrollPane2 = new javax.swing.JScrollPane();
      configTable = new javax.swing.JTable() {
         @Override
         public TableCellEditor getCellEditor(int row, int column) {
            if (column > OPTION_NAME && row >= 0 && row < editors.size()) {
               return editors.get(row);
            }
            return super.getCellEditor(row, column);
         }
      };

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      setTitle(bundle.getString("ServerConfigWindow.title")); // NOI18N

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      BtnClose.setToolTipText(bundle.getString("UsersWindow.btnClose.toolTipText")); // NOI18N
      BtnClose.setFocusable(false);
      BtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      BtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      BtnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnCloseActionPerformed(evt);
         }
      });
      jToolBar1.add(BtnClose);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diskette.png"))); // NOI18N
      btnSave.setToolTipText(bundle.getString("ServerConfigWindow.btnSave.toolTipText")); // NOI18N
      btnSave.setEnabled(false);
      btnSave.setFocusable(false);
      btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnSave.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveActionPerformed(evt);
         }
      });
      jToolBar2.add(btnSave);

      btnApply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok.png"))); // NOI18N
      btnApply.setToolTipText(bundle.getString("ServerConfigWindow.btnApply.msg")); // NOI18N
      btnApply.setDefaultCapable(false);
      btnApply.setEnabled(false);
      btnApply.setFocusable(false);
      btnApply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnApply.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnApply.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnApplyActionPerformed(evt);
         }
      });
      jToolBar2.add(btnApply);
      jToolBar2.add(jSeparator2);

      btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
      btnAdd.setToolTipText(bundle.getString("ServerConfigWindow.btnAdd.toolTipText")); // NOI18N
      btnAdd.setFocusable(false);
      btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddActionPerformed(evt);
         }
      });
      jToolBar2.add(btnAdd);

      btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancel.png"))); // NOI18N
      btnRemove.setToolTipText(bundle.getString("ServerConfigWindow.btnRemove.toolTipText")); // NOI18N
      btnRemove.setEnabled(false);
      btnRemove.setFocusable(false);
      btnRemove.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRemove.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRemove.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoveActionPerformed(evt);
         }
      });
      jToolBar2.add(btnRemove);
      jToolBar2.add(copyButtonsSep);

      btnCopyLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_left_32.png"))); // NOI18N
      btnCopyLeft.setToolTipText(bundle.getString("ServerConfigWindow.btnCopyLeft.toolTipText")); // NOI18N
      btnCopyLeft.setEnabled(false);
      btnCopyLeft.setFocusable(false);
      btnCopyLeft.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnCopyLeft.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnCopyLeft.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCopyLeftActionPerformed(evt);
         }
      });
      jToolBar2.add(btnCopyLeft);

      btnCopyToAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_left_right_32.png"))); // NOI18N
      btnCopyToAll.setToolTipText(bundle.getString("ServerConfigWindow.btnCopyToAll.toolTipText")); // NOI18N
      btnCopyToAll.setEnabled(false);
      btnCopyToAll.setFocusable(false);
      btnCopyToAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnCopyToAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnCopyToAll.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCopyToAllActionPerformed(evt);
         }
      });
      jToolBar2.add(btnCopyToAll);

      btnCopyRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow_right_32.png"))); // NOI18N
      btnCopyRight.setToolTipText(bundle.getString("ServerConfigWindow.btnCopyRight.toolTipText")); // NOI18N
      btnCopyRight.setEnabled(false);
      btnCopyRight.setFocusable(false);
      btnCopyRight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnCopyRight.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnCopyRight.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCopyRightActionPerformed(evt);
         }
      });
      jToolBar2.add(btnCopyRight);

      configTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      configTable.getTableHeader().setReorderingAllowed(false);
      configTable.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            configTableKeyPressed(evt);
         }
      });
      jScrollPane2.setViewportView(configTable);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addComponent(jScrollPane2)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
      if (btnSave.isEnabled()
              && JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("ServerConfigWindow.confirm_unsaved_changes.msg"),
                      TerminalUtil.getMessage("ServerConfigWindow.save_config.msg"), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
         saveConfig();
      }
      exit();
   }//GEN-LAST:event_BtnCloseActionPerformed

   private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      if (JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("ServerConfigWindow.confirm_save_changes.msg"),
              TerminalUtil.getMessage("ServerConfigWindow.save_config.msg"), JOptionPane.YES_NO_OPTION,
              JOptionPane.QUESTION_MESSAGE) == 0) {
         saveConfig();
      }
   }//GEN-LAST:event_btnSaveActionPerformed

   private void btnCopyLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyLeftActionPerformed
      final ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      final int col = configTable.getSelectedColumn();
      final int modelRow = configTable.convertRowIndexToModel(configTable.getSelectedRow());
      final Object value = model.getValueAt(modelRow, configTable.convertColumnIndexToModel(col));
      for (int i = col - 1; i > 0; i--) {
         model.setValueAt(value, modelRow, configTable.convertColumnIndexToModel(i));
      }
   }//GEN-LAST:event_btnCopyLeftActionPerformed

   private void btnCopyToAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyToAllActionPerformed
      btnCopyLeftActionPerformed(evt);
      btnCopyRightActionPerformed(evt);
   }//GEN-LAST:event_btnCopyToAllActionPerformed

   private void btnCopyRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyRightActionPerformed
      final ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      final int col = configTable.getSelectedColumn();
      final int modelRow = configTable.convertRowIndexToModel(configTable.getSelectedRow());
      final Object value = model.getValueAt(modelRow, configTable.convertColumnIndexToModel(col));
      for (int i = col + 1; i < configTable.getColumnCount(); i++) {
         model.setValueAt(value, modelRow, configTable.convertColumnIndexToModel(i));
      }
   }//GEN-LAST:event_btnCopyRightActionPerformed

   private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
      insertRow();
   }//GEN-LAST:event_btnAddActionPerformed

   private void insertRow() {
      final int tableRow;
      final ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      model.add("");
      editors.add(createTextEditor(""));
      tableRow = configTable.convertRowIndexToView(model.getRowCount() - 1);
      configTable.changeSelection(tableRow, 0, false, false);
      configTable.editCellAt(tableRow, 0);
   }

   private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
      deleteRow();
   }//GEN-LAST:event_btnRemoveActionPerformed

   private void deleteRow() {
      final ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      final int selectedCol = configTable.getSelectedColumn();
      final int selectedRow = configTable.getSelectedRow();
      final int modelRow = configTable.convertRowIndexToModel(selectedRow);
      model.delete(modelRow);
      editors.remove(modelRow);
      if (selectedRow < configTable.getRowCount()) {
         configTable.changeSelection(selectedRow, selectedCol, false, false);
      } else if (configTable.getRowCount() > 0) {
         configTable.changeSelection(configTable.getRowCount() - 1, selectedCol, false, false);
      }
   }

   private void configTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_configTableKeyPressed
      switch (evt.getKeyCode()) {
         case KeyEvent.VK_ESCAPE:
            cancelCellEditing();
            evt.consume();
            break;
         case KeyEvent.VK_ENTER:
            if (editSelectedCell(evt, false)) {
               evt.consume();
            }
            break;
         case KeyEvent.VK_DELETE:
            if (deleteSelectedRow(evt)) {
               evt.consume();
            }
            break;
         case KeyEvent.VK_INSERT:
            insertRow();
            evt.consume();
            break;
         case KeyEvent.VK_PASTE:
            if (editSelectedCell(evt, true)) {
               evt.consume();
            }
            break;
         case KeyEvent.VK_V:
            if (evt.isControlDown() && editSelectedCell(evt, true)) {
               evt.consume();
            }
            break;
         default:
            break;
      }

   }//GEN-LAST:event_configTableKeyPressed

   private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
      if (JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("ServerConfigWindow.confirm_apply_changes.msg"),
              TerminalUtil.getMessage("ServerConfigWindow.apply_config.msg"), JOptionPane.YES_NO_OPTION,
              JOptionPane.QUESTION_MESSAGE) == 0) {
         applyConfig();
      }
   }//GEN-LAST:event_btnApplyActionPerformed

   private void stopEditingCell() {
      if (configTable.getCellEditor() != null) {
         configTable.getCellEditor().stopCellEditing();
      }
   }

   private void cancelCellEditing() {
      if (configTable.isEditing() && configTable.getCellEditor() != null) {
         configTable.getCellEditor().cancelCellEditing();
      }
   }

   private void pasteClipboard(Component editor, String text) {
      if (TerminalUtil.isEmpty(text)) {
         return;
      }
      for (int i = 0; i < text.length(); i++) {
         final char c = text.charAt(i);
         editor.dispatchEvent(new KeyEvent(editor, KeyEvent.KEY_TYPED, System.currentTimeMillis(), 0, KeyEvent.VK_UNDEFINED, c));
      }
   }

   private void editCell(final int row, final int col, final boolean pasteClipboard) {
      Component editor;
      configTable.changeSelection(row, col, false, false);
      configTable.editCellAt(row, col);
      editor = configTable.getEditorComponent();
      if (editor != null) {
         if (pasteClipboard) {
            pasteClipboard(editor, TerminalUtil.getTextClipboard());
         }
         editor.requestFocus();
      }
   }

   private void editNextCell() {
      if (configTable.getRowCount() > 0) {
         int row = configTable.getSelectedRow();
         int col = configTable.getSelectedColumn() + 1;
         while (col < configTable.getColumnCount() && !configTable.isCellEditable(row, col)) {
            col++;
         }
         if (col < configTable.getColumnCount()) {
            editCell(row, col, false);
         }
      }
   }

   private boolean editSelectedCell(KeyEvent evt, boolean pasteClipboard) {
      int row;
      int col;
      if (configTable.getRowCount() <= 0) {
         return false;
      }
      row = configTable.getSelectedRow();
      col = configTable.getSelectedColumn();
      if (configTable.isEditing()) {
         if (row == configTable.getEditingRow() && col == configTable.getEditingColumn()) {
            stopEditingCell();
            editNextCell();
            return true;
         }
         stopEditingCell();
      }
      while (col < configTable.getColumnCount() && !configTable.isCellEditable(row, col)) {
         col++;
      }
      if (col >= configTable.getColumnCount()) {
         return false;
      }
      editCell(row, col, pasteClipboard);
      return true;
   }

   private boolean deleteSelectedRow(KeyEvent evt) {
      if (configTable.getRowCount() > 0 && !configTable.isEditing()) {
         deleteRow();
         return true;
      }
      return false;
   }

   private OptionType optionType(TerminalOption<?> terminalOption) {
      if (Boolean.class.isAssignableFrom(terminalOption.getType())) {
         return OptionType.BOOLEAN;
      } else if (Integer.class.isAssignableFrom(terminalOption.getType())) {
         return OptionType.INT;
      } else if (RGTLogLevel.class.isAssignableFrom(terminalOption.getType())) {
         return OptionType.LOG_LEVEL;
      }
      return OptionType.STRING;
   }

   private TextCellEditor createTextEditor(final String optionName) {
      final TextCellEditor editor = new TextCellEditor();
      editor.setTextAreaTitle(optionName);
      editor.addKeyListener(new DefaultCellKeyListener(configTable));
      return editor;
   }

   private CustomCellEditor createEditor(final ConfigOption option) {
      CustomCellEditor editor;
      switch (option.getType()) {
         case BOOLEAN: {
            editor = new ComboCellEditor<>(new String[]{"false", "true"});
            editor.addKeyListener(new DefaultCellKeyListener(configTable, COMBO_KEYS));
            break;
         }
         case INT:
            editor = new IntegerCellEditor(0);
            editor.addKeyListener(new DefaultCellKeyListener(configTable));
            break;
         case LOG_LEVEL: {
            editor = new ComboCellEditor(new String[]{
               RGTLogLevel.OFF.name(),
               RGTLogLevel.ERROR.name(),
               RGTLogLevel.WARNING.name(),
               RGTLogLevel.INFO.name(),
               RGTLogLevel.DEBUG.name(),
               RGTLogLevel.TRACE.name()});
            editor.addKeyListener(new DefaultCellKeyListener(configTable, COMBO_KEYS));
            break;
         }
         default: {
            editor = createTextEditor(option.getName());
            break;
         }
      }
      return editor;
   }

   private ConfigTableModel createModel() {
      final String[] columns;
      final List<String[]> data;
      final Set<ConfigOption> optionsSet = new HashSet<>();
      options.clear();
      for (RemoteTerminalServer server : servers) {
         final Map<String, String> optionsMap = server.getConfiguration().stringValues();
         for (Map.Entry<String, String> option : optionsMap.entrySet()) {
            final ConfigOption configOption = new ConfigOption(option.getKey());
            if (!optionsSet.contains(configOption)) {
               final TerminalOption<?> serverOp = server.getConfiguration().getOption(option.getKey());
               if (serverOp != null) {
                  configOption.setType(optionType(serverOp));
               }
               optionsSet.add(configOption);
            }
         }
      }
      options.addAll(optionsSet);
      Collections.sort(options, (o1, o2) -> o1.getName().compareToIgnoreCase(o2.getName()));
      columns = createColumnsHeaders();
      data = new ArrayList<>(options.size());
      editors.clear();

      for (int row = 0; row < options.size(); row++) {
         final ConfigOption option = options.get(row);
         final String[] rowData = new String[columns.length];
         editors.add(createEditor(option));
         data.add(rowData);
         setDataRow(option, rowData);
      }
      return new ConfigTableModel(columns, data);
   }

   private String[] createColumnsHeaders() {
      final String[] columns = new String[servers.size() + 1];
      columns[0] = TerminalUtil.getMessage("ServerConfigWindow.options.header");
      for (int i = 0; i < servers.size(); i++) {
         columns[i + 1] = servers.get(i).getId();
      }
      return columns;
   }

   private void setDataRow(final ConfigOption option, final String[] rowData) {
      rowData[0] = option.getName();
      for (int col = 1; col <= servers.size(); col++) {
         final RemoteTerminalServer server = servers.get(col - 1);
         String value = null;
         if (option.getName().toLowerCase().startsWith("env.")) {
            value = server.getConfiguration().getEnvVar(option.getName());
         } else {
            final TerminalOption<?> terminalOption = server.getConfiguration().getOption(option.getName());
            if (terminalOption != null) {
               value = terminalOption.text();
            }
         }
         rowData[col] = value != null ? value : "";
      }
   }

   private void configureConfigTable() {
      final TableColumnModel colModel;
      final ImageIcon diffIcon = new ImageIcon(getClass().getResource("/alert_16.png"));
      final ModifiedCellDecorator changeDecorator = new ModifiedCellDecorator().changedBackground(Color.CYAN);
      final ValueDiffDecorator diffDecorator = new ValueDiffDecorator(1).diffIcon(diffIcon).diffBackground(DIFF_CELL_BACKGROUND);
      final DecoratorTableCellRenderer cellRenderer = new DecoratorTableCellRenderer(diffDecorator, changeDecorator);
      final TextCellEditor optionNameEditor = new TextCellEditor();
      final ConfigTableModel model = createModel();

      optionNameEditor.addCellEditorListener(new ValidateDuplicatedKeyListener(configTable, 0,
              v -> JOptionPane.showMessageDialog(null,
                      TerminalUtil.getMessage("ServerConfigWindow.option_already_exists.msg"),
                      TerminalUtil.getMessage("ServerConfigWindow.option_already_exists.title"),
                      JOptionPane.WARNING_MESSAGE),
              true,
              true));
      optionNameEditor.addKeyListener(new DefaultCellKeyListener(configTable));
      configTable.setModel(model);
      configTable.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
      colModel = configTable.getColumnModel();
      colModel.getColumn(OPTION_NAME).setResizable(true);
      colModel.getColumn(OPTION_NAME).setPreferredWidth(calcColumnSize(OPTION_NAME));
      colModel.getColumn(OPTION_NAME).setCellEditor(optionNameEditor);
      colModel.getColumn(OPTION_NAME).setCellRenderer(cellRenderer);
      for (int i = 0; i < servers.size(); i++) {
         colModel.getColumn(i + 1).setResizable(true);
         colModel.getColumn(i + 1).setPreferredWidth(250);
         colModel.getColumn(i + 1).setCellRenderer(cellRenderer);
      }
      configTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      configTable.setColumnSelectionAllowed(false);
      configTable.setRowSelectionAllowed(false);
      configTable.setCellSelectionEnabled(true);
      configTable.setColumnSelectionInterval(0, 0);
      configTable.setRowSelectionInterval(0, 0);
      copyButtonsSep.setVisible(model.getColumnCount() > 2);
      btnCopyLeft.setVisible(model.getColumnCount() > 2);
      btnCopyRight.setVisible(model.getColumnCount() > 2);
      btnCopyToAll.setVisible(model.getColumnCount() > 2);
      configTable.getModel().addTableModelListener((TableModelEvent e) -> {
         btnSave.setEnabled(model.isChanged());
         btnApply.setEnabled(model.isChanged());
      });
      configTable.getColumnModel().addColumnModelListener(this);
      configTable.getSelectionModel().addListSelectionListener(this);
   }

   private int calcColumnSize(int col) {
      int width = 0;
      for (int row = 0; row < configTable.getRowCount(); row++) {
         TableCellRenderer renderer = configTable.getCellRenderer(row, col);
         Component comp = configTable.prepareRenderer(renderer, row, col);
         width = Math.max(comp.getPreferredSize().width + 6, width);
      }
      return width;
   }

   private void applyConfig() {
      final List<RemoteTerminalServer> serversErrors = new ArrayList<>();
      ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      for (String optionName : model.removed()) {
         servers.forEach(s -> s.getConfiguration().delete(optionName));
      }
      // update options
      for (int row = 0; row < model.getRowCount(); row++) {
         if (model.isChanged(row)) {
            setServerValues(model, row);
         }
      }
      for (RemoteTerminalServer s : servers) {
         try {
            if (!s.setRemoteConfiguration()) {
               serversErrors.add(s);
            }
         } catch (TerminalException ex) {
            serversErrors.add(s);
            message(TerminalUtil.getMessage("ServerConfigWindow.applying_error.msg", s), "\n",
                    ex.getMessage(),
                    "\n================================================================================\n");
         }
      }
      if (!serversErrors.isEmpty()) {
         serversErrors.forEach(s -> reloadConfiguration(s));
         JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("ServerConfigWindow.alert_applying_error.msg"),
                 TerminalUtil.getMessage("ServerConfigWindow.alert_applying_error.title"), JOptionPane.ERROR_MESSAGE);
         configureConfigTable();
      }
      model.clearChanges();
      btnSave.setEnabled(false);
      btnApply.setEnabled(false);
   }

   private void saveConfig() {
      final List<RemoteTerminalServer> serversErrors = new ArrayList<>();
      ConfigTableModel model = (ConfigTableModel) configTable.getModel();
      for (String optionName : model.removed()) {
         servers.forEach(s -> s.getConfiguration().delete(optionName));
      }
      // update options
      for (int row = 0; row < model.getRowCount(); row++) {
         if (model.isChanged(row)) {
            setServerValues(model, row);
         }
      }
      for (RemoteTerminalServer s : servers) {
         try {
            if (!s.saveConfiguration()) {
               serversErrors.add(s);
            }
         } catch (TerminalException ex) {
            serversErrors.add(s);
            message(TerminalUtil.getMessage("ServerConfigWindow.saving_error.msg", s), "\n",
                    ex.getMessage(),
                    "\n================================================================================\n");
         }
      }
      if (!serversErrors.isEmpty()) {
         serversErrors.forEach(s -> reloadConfiguration(s));
         JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("ServerConfigWindow.alert_saving_error.msg"),
                 TerminalUtil.getMessage("ServerConfigWindow.alert_saving_error.title"), JOptionPane.ERROR_MESSAGE);
         configureConfigTable();
      }
      model.clearChanges();
      btnSave.setEnabled(false);
      btnApply.setEnabled(false);
   }

   private void reloadConfiguration(RemoteTerminalServer s) {
      if (s.isConnected()) {
         message(TerminalUtil.getMessage("ServerConfigWindow.reload_config.msg", s), "\n");
         try {
            s.loadConfiguration();
         } catch (TerminalException ex) {
            message(TerminalUtil.getMessage("ServerMainWindow.error_load_config.msg", s), "\n",
                    ex.getMessage(),
                    "\n================================================================================\n");
         }
      }
   }

   private void setServerValues(ConfigTableModel model, int row) {
      final String optionName = model.getOptionName(row);
      if (TerminalUtil.isEmpty(optionName)) {
         return;
      }
      for (int col = 1; col <= servers.size(); col++) {
         if (model.isChanged(row, col)) {
            servers.get(col - 1).getConfiguration().setValue(optionName, model.getValueAt(row, col).toString());
         }
      }
   }

   private void exit() {
      setVisible(false);
      dispose();
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnClose;
   private javax.swing.JButton btnAdd;
   private javax.swing.JButton btnApply;
   private javax.swing.JButton btnCopyLeft;
   private javax.swing.JButton btnCopyRight;
   private javax.swing.JButton btnCopyToAll;
   private javax.swing.JButton btnRemove;
   private javax.swing.JButton btnSave;
   private javax.swing.JTable configTable;
   private javax.swing.JToolBar.Separator copyButtonsSep;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JToolBar.Separator jSeparator2;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   // End of variables declaration//GEN-END:variables

   private void enableButtons() {
      final int col = configTable.getSelectedColumn();
      final int row = configTable.getSelectedRow();
      btnCopyLeft.setEnabled(col > 1);
      btnCopyRight.setEnabled(col > 0 && col < configTable.getColumnCount() - 1);
      btnCopyToAll.setEnabled(btnCopyLeft.isEnabled() && btnCopyRight.isEnabled());
      btnRemove.setEnabled(row >= 0 && row < configTable.getRowCount());
   }

   public void message(Object... values) {
      if (notifier != null) {
         notifier.message(values);
      }
   }

   @Override
   public void columnAdded(TableColumnModelEvent e) {
      // ignore
   }

   @Override
   public void columnRemoved(TableColumnModelEvent e) {
      // ignore
   }

   @Override
   public void columnMoved(TableColumnModelEvent e) {
      // ignore
   }

   @Override
   public void columnMarginChanged(ChangeEvent e) {
      // ignore
   }

   @Override
   public void columnSelectionChanged(ListSelectionEvent e) {
      enableButtons();
   }

   @Override
   public void valueChanged(ListSelectionEvent e) {
      enableButtons();
   }
}
