/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.rgt.gui;

import java.awt.Component;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import org.rgt.CancelableExecutor;
import org.rgt.ServerStatus;
import org.rgt.Session;
import org.rgt.TerminalException;
import org.rgt.TerminalServer;
import org.rgt.TerminalServerListener;
import org.rgt.TerminalUtil;
import org.rgt.client.SessionStats;

/**
 *
 * @author fabio
 */
public class SessionDetailsWindow extends javax.swing.JDialog implements TerminalServerListener {

   private static final Map<Session, SessionDetailsWindow> viewingSessions = Collections.synchronizedMap(new HashMap<>());

   private final TerminalServer server;

   private final Session session;

   private final CancelableExecutor executor;

   final ResourceBundle bundle;

   private SessionDetailsWindow(javax.swing.JDialog parent, final TerminalServer server, final Session session, final CancelableExecutor executor) {
      super(parent, false);
      this.server = server;
      this.session = session;
      this.executor = executor;
      initComponents();
      bundle = ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      topPanel = new javax.swing.JPanel();
      jToolBar1 = new javax.swing.JToolBar();
      btnRefresh = new javax.swing.JButton();
      jToolBar2 = new javax.swing.JToolBar();
      btnClose = new javax.swing.JButton();
      jPanel1 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      statsTable = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosed(java.awt.event.WindowEvent evt) {
            formWindowClosed(evt);
         }
      });

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      btnRefresh.setToolTipText(bundle.getString("ViewSessionWindow.btnRefresh.toolTipText")); // NOI18N
      btnRefresh.setFocusable(false);
      btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRefresh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
         }
      });
      jToolBar1.add(btnRefresh);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      btnClose.setToolTipText(bundle.getString("SessionsWindow.btnClose.toolTipText")); // NOI18N
      btnClose.setFocusable(false);
      btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });
      jToolBar2.add(btnClose);

      javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
      topPanel.setLayout(topPanelLayout);
      topPanelLayout.setHorizontalGroup(
         topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(topPanelLayout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      topPanelLayout.setVerticalGroup(
         topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      statsTable.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {

         }
      ));
      statsTable.getTableHeader().setReorderingAllowed(false);
      jScrollPane1.setViewportView(statsTable);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(0, 0, 0)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      exit();
      server.removeListener(this);
   }//GEN-LAST:event_formWindowClosed

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      executor.execute(this::refreshStats);
   }//GEN-LAST:event_btnRefreshActionPerformed

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      exit();
   }//GEN-LAST:event_btnCloseActionPerformed

   public static void viewSession(final TerminalServer server, final Session session, final CancelableExecutor executor) {
      try {
         SessionDetailsWindow win = viewingSessions.get(session);
         if (win == null) {
            final SessionStats stats = server.getSessionStats(session.getId());
            win = new SessionDetailsWindow(null, server, session, executor);
            viewingSessions.put(session, win);
            server.addListener(win);
            TerminalUtil.centralize(null, win);
            win.updateStats(stats);
            win.setTitle(session.getId() + " - " + session.getTerminalAddress() + " - " + session.getOSUser() + " - " + session.getAppPid());
            win.setVisible(true);
         } else {
            win.toFront();
            win.repaint();
         }
      } catch (TerminalException ex) {
         JOptionPane.showMessageDialog(null,
                 TerminalUtil.getMessage("ViewSessionStatsWindow.update_eror.msg") + ":\n" + ex.getMessage(),
                 TerminalUtil.getMessage("ViewSessionStatsWindow.update_eror.title"),
                 JOptionPane.ERROR_MESSAGE);
      }
   }

   @Override
   public void notification(TerminalServer server, String message) {
      // do nothing
   }

   @Override
   public void configurationLoaded(TerminalServer server) {
      // do nothing
   }

   @Override
   public void configurationSaved(TerminalServer server) {
      // do nothing
   }

   @Override
   public void stateUpdate(TerminalServer server) {
      // do nothing
   }

   @Override
   public void statusChanged(TerminalServer server, ServerStatus previousStatus) {
      // do nothing
   }

   @Override
   public void sessionOpen(Session session) {
      // do nothing
   }

   @Override
   public void sessionClose(Session session) {
      exit();
   }

   @Override
   public void serviceStart(TerminalServer server) {
      // do nothing
   }

   @Override
   public void serviceStop(TerminalServer server) {
      exit();
   }

   private void exit() {
      if (viewingSessions.containsKey(session)) {
         viewingSessions.remove(session);
         executor.clear();
         java.awt.EventQueue.invokeLater(() -> setVisible(false));
      }
   }

   private void updateStats(final SessionStats stats) {
      final DefaultTableModel model;
      final String columns[] = new String[]{"info", "value"};
      final String[][] data = new String[][]{
         statValue("ViewSessionStatsWindow.terminal.bytesReceived", TerminalUtil.formatSize(stats.getBytesReceivedFromTerminal())),
         statValue("ViewSessionStatsWindow.terminal.bytesSent", TerminalUtil.formatSize(stats.getBytesSentToTerminal())),
         statValue("ViewSessionStatsWindow.terminal.packetsReceived", stats.getPacketsReceivedFromTerminal()),
         statValue("ViewSessionStatsWindow.terminal.packetsSent", stats.getPacketsSentToTerminal()),
         statValue("ViewSessionStatsWindow.app.bytesReceived", TerminalUtil.formatSize(stats.getBytesReceivedFromApplication())),
         statValue("ViewSessionStatsWindow.app.bytesSent", TerminalUtil.formatSize(stats.getBytesSentToApplication())),
         statValue("ViewSessionStatsWindow.app.packetsReceived", stats.getPacketsReceivedFromApplication()),
         statValue("ViewSessionStatsWindow.app.packetsSent", stats.getPacketsSentToApplication())
      };
//      final ArrayList<String[]> data = new ArrayList<>();
//      data.add(statValue("ViewSessionStatsWindow.terminal.bytesReceived", stats.getBytesReceivedFromTerminal()));
//      data.add(statValue("ViewSessionStatsWindow.terminal.bytesSent", stats.getBytesSentToTerminal()));
//      data.add(statValue("ViewSessionStatsWindow.terminal.packetsReceived", stats.getPacketsReceivedFromTerminal()));
//      data.add(statValue("ViewSessionStatsWindow.terminal.packetsSent", stats.getPacketsSentToTerminal()));
//      data.add(statValue("ViewSessionStatsWindow.app.bytesReceived", stats.getBytesReceivedFromApplication()));
//      data.add(statValue("ViewSessionStatsWindow.app.bytesSent", stats.getBytesSentToApplication()));
//      data.add(statValue("ViewSessionStatsWindow.app.packetsReceived", stats.getPacketsReceivedFromApplication()));
//      data.add(statValue("ViewSessionStatsWindow.app.packetsSent", stats.getPacketsSentToApplication()));
      model = new DefaultTableModel(data, columns);
      statsTable.getTableHeader().setVisible(false);
      statsTable.setModel(model);
      resizeColumnWidth(statsTable);
   }

   private String[] statValue(final String statLabel, final long value) {
      return new String[]{bundle.getString(statLabel), Long.toString(value)};
   }

   private String[] statValue(final String statLabel, final String value) {
      return new String[]{bundle.getString(statLabel), value};
   }

   private void resizeColumnWidth(JTable table) {
      final TableColumnModel columnModel = table.getColumnModel();
      for (int column = 0; column < table.getColumnCount(); column++) {
         int width = 30; // Min width
         for (int row = 0; row < table.getRowCount(); row++) {
            TableCellRenderer renderer = table.getCellRenderer(row, column);
            Component comp = table.prepareRenderer(renderer, row, column);
            width = Math.max(comp.getPreferredSize().width + 1, width);
         }
         columnModel.getColumn(column).setPreferredWidth(width);
      }
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnRefresh;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private javax.swing.JTable statsTable;
   private javax.swing.JPanel topPanel;
   // End of variables declaration//GEN-END:variables

   private void refreshStats() {
      try {
         updateStats(server.getSessionStats(session.getId()));
      } catch (TerminalException ex) {
         JOptionPane.showMessageDialog(null,
                 TerminalUtil.getMessage("ViewSessionStatsWindow.update_eror.msg") + ":\n" + ex.getMessage(),
                 TerminalUtil.getMessage("ViewSessionStatsWindow.update_eror.title"),
                 JOptionPane.ERROR_MESSAGE);
      }
   }
}
