/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rgt.gui;

import org.rgt.Session;
import org.rgt.TerminalException;
import org.rgt.gui.table.SessionTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableColumnModel;
import org.rgt.TerminalServer;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.Collection;
import org.rgt.CancelableExecutor;
import org.rgt.TerminalUtil;
import org.rgt.gui.table.TableFilter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author fabio_uggeri
 */
public class SessionsWindow extends javax.swing.JDialog {

   private static final long serialVersionUID = -8611426852282705649L;

   private static final Logger LOG = LoggerFactory.getLogger(SessionsWindow.class);

   private static final int SESSION_ID = 0;
   private static final int SESSION_TE_ADDRESS = 1;
   private static final int SESSION_USER = 2;
   private static final int SESSION_PID = 3;
   private static final int SESSION_STATUS = 4;
   private static final int SESSION_LOGON_TIME = 5;
   private static final int SESSION_CMD_LINE = 6;

   private final TerminalServer server;

   private final CancelableExecutor executor;

   /**
    * Creates new form SessionsWindow
    * @param parent
    * @param server
    * @param executor
    */
   public SessionsWindow(final java.awt.Frame parent, final TerminalServer server, final CancelableExecutor executor) {
      super(parent, true);
      initComponents();
      this.server = server;
      this.executor = executor;
      initSessionsWindow();
   }

   private void initSessionsWindow() {
      Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
      setLocation((tela.width - getSize().width) / 2, (tela.height - getSize().height) / 2);
      configureSessionsTable();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      jToolBar1 = new javax.swing.JToolBar();
      btnKill = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JToolBar.Separator();
      btnRefresh = new javax.swing.JButton();
      btnViewScreen = new javax.swing.JButton();
      jToolBar2 = new javax.swing.JToolBar();
      btnClose = new javax.swing.JButton();
      jPanel2 = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      sessionsTable = new javax.swing.JTable();
      jPanel3 = new javax.swing.JPanel();
      jLabel7 = new javax.swing.JLabel();
      sessionsCount = new javax.swing.JFormattedTextField();
      jLabel8 = new javax.swing.JLabel();
      selectedCount = new javax.swing.JFormattedTextField();

      jLabel1.setText("jLabel1");

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      setTitle(bundle.getString("SessionsWindow.title")); // NOI18N
      setIconImage(new javax.swing.ImageIcon(getClass().getResource("/sessions.png")).getImage());
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosed(java.awt.event.WindowEvent evt) {
            formWindowClosed(evt);
         }
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      btnKill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close_session.png"))); // NOI18N
      btnKill.setToolTipText(bundle.getString("SessionsWindow.btnKill.toolTipText")); // NOI18N
      btnKill.setEnabled(false);
      btnKill.setFocusable(false);
      btnKill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnKill.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnKill.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnKillActionPerformed(evt);
         }
      });
      jToolBar1.add(btnKill);
      jToolBar1.add(jSeparator1);

      btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
      btnRefresh.setToolTipText(bundle.getString("SessionsWindow.btnRefresh.toolTipText")); // NOI18N
      btnRefresh.setFocusable(false);
      btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRefresh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
         }
      });
      jToolBar1.add(btnRefresh);

      btnViewScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prompt.png"))); // NOI18N
      btnViewScreen.setToolTipText(bundle.getString("SessionsWindow.btnViewScreen.toolTipText")); // NOI18N
      btnViewScreen.setEnabled(false);
      btnViewScreen.setFocusable(false);
      btnViewScreen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnViewScreen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnViewScreen.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnViewScreenActionPerformed(evt);
         }
      });
      jToolBar1.add(btnViewScreen);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      btnClose.setToolTipText(bundle.getString("SessionsWindow.btnClose.toolTipText")); // NOI18N
      btnClose.setFocusable(false);
      btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });
      jToolBar2.add(btnClose);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SessionsWindow.sessionPanel.label"))); // NOI18N

      sessionsTable.setModel(new SessionTableModel());
      sessionsTable.setColumnSelectionAllowed(true);
      sessionsTable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
      sessionsTable.getTableHeader().setReorderingAllowed(false);
      sessionsTable.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            sessionsTableKeyPressed(evt);
         }
      });
      jScrollPane1.setViewportView(sessionsTable);
      sessionsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
      );

      jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

      jLabel7.setText(bundle.getString("SessionsWindow.status_bar.sessions.label")); // NOI18N

      sessionsCount.setEditable(false);
      sessionsCount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      sessionsCount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
      sessionsCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      sessionsCount.setText("0");
      sessionsCount.setFocusable(false);

      jLabel8.setText(bundle.getString("SessionsWindow.status_bar.selected.label")); // NOI18N

      selectedCount.setEditable(false);
      selectedCount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      selectedCount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
      selectedCount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      selectedCount.setText("0");
      selectedCount.setFocusable(false);

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sessionsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(selectedCount, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(9, 9, 9))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel7)
            .addComponent(sessionsCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8)
            .addComponent(selectedCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
   }//GEN-LAST:event_formWindowClosed

   private void btnKillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKillActionPerformed
      executor.execute(() -> killSelectedSessions());
   }//GEN-LAST:event_btnKillActionPerformed

   private void killSelectedSessions() throws HeadlessException {
      final int[] selectedRows = sessionsTable.getSelectedRows();
      if (JOptionPane.showConfirmDialog(null, TerminalUtil.getMessage("SessionsWindow.confirm_kill.msg", selectedRows.length),
              TerminalUtil.getMessage("SessionsWindow.kill_sessions.msg"), JOptionPane.YES_NO_OPTION,
              JOptionPane.QUESTION_MESSAGE) == 0) {
         try {
            killSessions(selectedRows);
         } catch (TerminalException ex) {
            LOG.error("Error killing session", ex);
            JOptionPane.showMessageDialog(null, TerminalUtil.getMessage("SessionsWindow.error_kill_sessions.msg") + ex.getMessage(),
                    TerminalUtil.getMessage("SessionsWindow.server_error.msg"), JOptionPane.ERROR_MESSAGE);
            if (!server.isEmbedded() && !server.isConnected()) {
               exit();
            }
         }
      }
   }

   private void killSessions(final int[] selectedRows) throws TerminalException, HeadlessException {
      final SessionTableModel model = (SessionTableModel) sessionsTable.getModel();
      final long[] selectedIds = new long[selectedRows.length];
      int killCount = 0;
      for (int i = 0; i < selectedRows.length; i++) {
         final Session s = model.getSession(sessionsTable.convertRowIndexToModel(selectedRows[i]));
         selectedIds[i] = s != null ? s.getId() : 0L;
      }
      for (long id : selectedIds) {
         if (id > 0) {
            if (server.killSession(id)) {
               ++killCount;
               model.removeSession(id);
            }
         }
      }
      sessionsCount.setText(Integer.toString(server.getSessionsCount()));
      JOptionPane.showMessageDialog(null, TerminalUtil.getMessage("SessionsWindow.sessions_killed.msg", killCount),
              TerminalUtil.getMessage("SessionsWindow.killed_sessions_title.msg"), JOptionPane.INFORMATION_MESSAGE);
   }

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      executor.execute(() -> {
         try {
            loadSessions();
            sessionsTable.requestFocus();
         } catch (TerminalException ex) {
            LOG.error("Error getting sessions", ex);
            JOptionPane.showMessageDialog(null, TerminalUtil.getMessage("SessionsWindow.error_get_sessions.msg") +
                    ex.getMessage(), TerminalUtil.getMessage("SessionsWindow.server_error.msg"),
                    JOptionPane.ERROR_MESSAGE);
            if (! server.isEmbedded() && ! server.isConnected()) {
               exit();
            }
         }
      });
   }//GEN-LAST:event_btnRefreshActionPerformed

   private void loadSessions() throws TerminalException {
      final SessionTableModel model = (SessionTableModel) sessionsTable.getModel();
      model.clearSessions(false);
      model.addSessions((Collection<Session>)server.getSessions(), false);
      model.fireTableDataChanged();
      sessionsCount.setText(Integer.toString(server.getSessionsCount()));
   }

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      exit();
   }//GEN-LAST:event_btnCloseActionPerformed

   private void sessionsTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sessionsTableKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
         killSelectedSessions();
      }
   }//GEN-LAST:event_sessionsTableKeyPressed

   private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      executor.execute(() -> {
         try {
            loadSessions();
            sessionsTable.requestFocus();
         } catch (TerminalException ex) {
            LOG.error("Error getting sessions", ex);
            JOptionPane.showMessageDialog(null, TerminalUtil.getMessage("SessionsWindow.error_get_sessions.msg") +
                    ex.getMessage(), TerminalUtil.getMessage("SessionsWindow.server_error.msg"),
                    JOptionPane.ERROR_MESSAGE);
            if (! server.isEmbedded() && ! server.isConnected()) {
               exit();
            }
         }
      });
   }//GEN-LAST:event_formWindowOpened

   private void btnViewScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewScreenActionPerformed
      viewSelectedSessions();
   }//GEN-LAST:event_btnViewScreenActionPerformed

   private void viewSelectedSessions() throws HeadlessException {
      final int[] selectedRows = sessionsTable.getSelectedRows();
      final SessionTableModel model = (SessionTableModel) sessionsTable.getModel();
      for (int i = 0; i < selectedRows.length; i++) {
         final Session s = model.getSession(sessionsTable.convertRowIndexToModel(selectedRows[i]));
         if (s != null) {
            viewSession(s);
         }
      }
   }

   private void viewSession(final Session session) {
      ViewSessionWindow.viewSession(server, session, executor);
   }

   private void exit() {
      setVisible(false);
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnKill;
   private javax.swing.JButton btnRefresh;
   private javax.swing.JButton btnViewScreen;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JToolBar.Separator jSeparator1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private javax.swing.JFormattedTextField selectedCount;
   private javax.swing.JFormattedTextField sessionsCount;
   private javax.swing.JTable sessionsTable;
   // End of variables declaration//GEN-END:variables

   private void configureSessionsTable() {
      TableColumnModel colModel = sessionsTable.getColumnModel();
      colModel.getColumn(SESSION_ID).setResizable(true);
      colModel.getColumn(SESSION_TE_ADDRESS).setResizable(true);
      colModel.getColumn(SESSION_USER).setResizable(true);
      colModel.getColumn(SESSION_PID).setResizable(true);
      colModel.getColumn(SESSION_STATUS).setResizable(true);
      colModel.getColumn(SESSION_LOGON_TIME).setResizable(true);
      colModel.getColumn(SESSION_CMD_LINE).setResizable(true);
      colModel.getColumn(SESSION_ID).setPreferredWidth(30);
      colModel.getColumn(SESSION_TE_ADDRESS).setPreferredWidth(90);
      colModel.getColumn(SESSION_USER).setPreferredWidth(100);
      colModel.getColumn(SESSION_PID).setPreferredWidth(50);
      colModel.getColumn(SESSION_STATUS).setPreferredWidth(40);
      colModel.getColumn(SESSION_LOGON_TIME).setPreferredWidth(120);
      colModel.getColumn(SESSION_CMD_LINE).setPreferredWidth(450);
      sessionsTable.setColumnSelectionAllowed(false);
      sessionsTable.setRowSelectionAllowed(true);
      sessionsTable.getSelectionModel().addListSelectionListener(new SessionSelectionListener());
      TableFilter.forTable(sessionsTable).apply().repaint();
   }

   private class SessionSelectionListener implements ListSelectionListener {

      @Override
      public void valueChanged(ListSelectionEvent e) {
         if (!e.getValueIsAdjusting()) {
            selectedCount.setText(Integer.toString(sessionsTable.getSelectedRowCount()));
            btnKill.setEnabled(! server.isReadOnly() && sessionsTable.getSelectedRowCount() > 0);
            btnViewScreen.setEnabled(sessionsTable.getSelectedRowCount() > 0);
         }
      }

   }
}
