/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.rgt.gui;

import org.rgt.auth.AuthenticatorException;
import org.rgt.auth.TerminalUser;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.rgt.TerminalServer;
import org.rgt.TerminalUtil;
import org.rgt.auth.UserAuthenticator;
import org.rgt.auth.UserRepository;

/**
 *
 * @author fabio_uggeri
 */
public class UsersWindow extends javax.swing.JDialog {

   private static final long serialVersionUID = -3454658086657592710L;

   private static final Logger LOG = LoggerFactory.getLogger(UsersWindow.class);

   private final TerminalServer server;

   private UserAuthenticator authenticator = null;
   private UserRepository usersRepository = null;

   /**
    * Creates new form UsersWindow
    * @param parent
    * @param server
    */
   public UsersWindow(java.awt.Frame parent, TerminalServer server) {
      super(parent, true);
      Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();
      initComponents();
      setLocation((tela.width - getSize().width) / 2, (tela.height - getSize().height) / 2);
      this.server = server;
      configureComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      usersPanel = new javax.swing.JPanel();
      jScrollPane1 = new javax.swing.JScrollPane();
      usersList = new javax.swing.JList<>();
      userDetailsPanel = new javax.swing.JPanel();
      usernameLabel = new javax.swing.JLabel();
      pswdLabel = new javax.swing.JLabel();
      pswdConfirmLabel = new javax.swing.JLabel();
      username = new javax.swing.JTextField();
      password = new javax.swing.JPasswordField();
      passwordConfirm = new javax.swing.JPasswordField();
      expiration = new org.jdesktop.swingx.JXDatePicker();
      chkExpiration = new javax.swing.JCheckBox();
      jToolBar3 = new javax.swing.JToolBar();
      btnConfirmUser = new javax.swing.JButton();
      jSeparator1 = new javax.swing.JToolBar.Separator();
      btnClearUser = new javax.swing.JButton();
      jToolBar1 = new javax.swing.JToolBar();
      BtnClose = new javax.swing.JButton();
      jToolBar2 = new javax.swing.JToolBar();
      btnSaveUsersList = new javax.swing.JButton();
      jSeparator2 = new javax.swing.JToolBar.Separator();
      btnRemoveUser = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      setTitle(bundle.getString("UsersWindow.title")); // NOI18N
      setAlwaysOnTop(true);
      setIconImage(new javax.swing.ImageIcon(getClass().getResource("/users.png")).getImage());

      usersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("UsersWindow.usersPanel.label"))); // NOI18N

      usersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
         public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            usersListValueChanged(evt);
         }
      });
      jScrollPane1.setViewportView(usersList);

      userDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("UsersWindow.usersPanel.userDetailsPanel.label"))); // NOI18N

      usernameLabel.setText(bundle.getString("UsersWindow.usersPanel.usernameLabel.label")); // NOI18N

      pswdLabel.setText(bundle.getString("UsersWindow.usersPanel.password.label")); // NOI18N

      pswdConfirmLabel.setText(bundle.getString("UsersWindow.usersPanel.passwordConfirm.label")); // NOI18N

      expiration.setEnabled(false);

      chkExpiration.setText(bundle.getString("UsersWindow.usersPanel.chkExpiration.label")); // NOI18N
      chkExpiration.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            chkExpirationActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout userDetailsPanelLayout = new javax.swing.GroupLayout(userDetailsPanel);
      userDetailsPanel.setLayout(userDetailsPanelLayout);
      userDetailsPanelLayout.setHorizontalGroup(
         userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(userDetailsPanelLayout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(pswdLabel, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(pswdConfirmLabel, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(chkExpiration, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(userDetailsPanelLayout.createSequentialGroup()
                  .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(password)
                     .addComponent(passwordConfirm)
                     .addComponent(expiration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(10, 10, 10))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailsPanelLayout.createSequentialGroup()
                  .addComponent(username)
                  .addContainerGap())))
      );
      userDetailsPanelLayout.setVerticalGroup(
         userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(userDetailsPanelLayout.createSequentialGroup()
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(usernameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(pswdLabel))
            .addGap(4, 4, 4)
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(passwordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(pswdConfirmLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(userDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(chkExpiration)
               .addComponent(expiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(0, 10, Short.MAX_VALUE))
      );

      jToolBar3.setRollover(true);

      btnConfirmUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok.png"))); // NOI18N
      btnConfirmUser.setToolTipText(bundle.getString("UsersWindow.usersPanel.btnSaveUser.toolTipText")); // NOI18N
      btnConfirmUser.setEnabled(false);
      btnConfirmUser.setFocusable(false);
      btnConfirmUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnConfirmUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnConfirmUser.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConfirmUserActionPerformed(evt);
         }
      });
      jToolBar3.add(btnConfirmUser);
      jToolBar3.add(jSeparator1);

      btnClearUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eraser.png"))); // NOI18N
      btnClearUser.setToolTipText(bundle.getString("UsersWindow.usersPanel.btnEraser.toolTipText")); // NOI18N
      btnClearUser.setFocusable(false);
      btnClearUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnClearUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnClearUser.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnClearUserActionPerformed(evt);
         }
      });
      jToolBar3.add(btnClearUser);

      javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
      usersPanel.setLayout(usersPanelLayout);
      usersPanelLayout.setHorizontalGroup(
         usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(usersPanelLayout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(userDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
      );
      usersPanelLayout.setVerticalGroup(
         usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPane1)
         .addGroup(usersPanelLayout.createSequentialGroup()
            .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(userDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      BtnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      BtnClose.setToolTipText(bundle.getString("UsersWindow.btnClose.toolTipText")); // NOI18N
      BtnClose.setFocusable(false);
      BtnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      BtnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      BtnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnCloseActionPerformed(evt);
         }
      });
      jToolBar1.add(BtnClose);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnSaveUsersList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diskette.png"))); // NOI18N
      btnSaveUsersList.setToolTipText(bundle.getString("UsersWindow.btnSave.toolTipText")); // NOI18N
      btnSaveUsersList.setEnabled(false);
      btnSaveUsersList.setFocusable(false);
      btnSaveUsersList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnSaveUsersList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnSaveUsersList.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSaveUsersListActionPerformed(evt);
         }
      });
      jToolBar2.add(btnSaveUsersList);
      jToolBar2.add(jSeparator2);

      btnRemoveUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user_delete.png"))); // NOI18N
      btnRemoveUser.setToolTipText(bundle.getString("UsersWindow.btnRemoveUser.toolTipText")); // NOI18N
      btnRemoveUser.setEnabled(false);
      btnRemoveUser.setFocusable(false);
      btnRemoveUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRemoveUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoveUserActionPerformed(evt);
         }
      });
      jToolBar2.add(btnRemoveUser);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
         .addComponent(usersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(usersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void BtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCloseActionPerformed
      if (btnSaveUsersList.isEnabled()
              && JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("UsersWindow.confirm_unsaved_changes.msg"),
                      TerminalUtil.getMessage("UsersWindow.save_users.msg"), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
         saveUsers();
      }
      exit();
   }//GEN-LAST:event_BtnCloseActionPerformed

   private void chkExpirationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkExpirationActionPerformed
      btnConfirmUser.setEnabled(! server.isReadOnly());
      expiration.setEnabled(chkExpiration.isSelected() && ! server.isReadOnly());
      if (chkExpiration.isEnabled() && expiration.getEditor().getText().isEmpty()) {
         final Calendar c = Calendar.getInstance();
         c.setTimeInMillis(System.currentTimeMillis());
         c.add(Calendar.DAY_OF_MONTH, 90);
         expiration.setDate(c.getTime());
      }
   }//GEN-LAST:event_chkExpirationActionPerformed

   private void btnClearUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUserActionPerformed
      btnConfirmUser.setEnabled(false);
      username.setText("");
      username.requestFocus();
      password.setText("");
      passwordConfirm.setText("");
      chkExpiration.setSelected(false);
      expiration.getEditor().setText("");
   }//GEN-LAST:event_btnClearUserActionPerformed

   private void btnConfirmUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmUserActionPerformed
      if (isValuesFieldsValid()) {
         final TerminalUserListModel model = (TerminalUserListModel)usersList.getModel();
         TerminalUser user = model.findUser(username.getText().trim());
         try {
            if (user == null) {
               user = new TerminalUser(username.getText().trim(), authenticator.encrypt(new String(password.getPassword())));
               model.addUser(user);
            } else {
               user.setPassword(authenticator.encrypt(new String(password.getPassword())));
            }
         } catch (AuthenticatorException ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                    TerminalUtil.getMessage("UsersWindow.error_setting_user.msg"), JOptionPane.ERROR_MESSAGE);
            LOG.error("Error setting user data.", ex);
            return;
         }
         if (chkExpiration.isSelected()) {
            user.setExpiration(expiration.getDate());
         } else {
            user.setExpiration(null);
         }
         clearFields();
         btnSaveUsersList.setEnabled(! server.isReadOnly());
         username.requestFocus();
         btnConfirmUser.setEnabled(false);
      }
   }//GEN-LAST:event_btnConfirmUserActionPerformed

   private boolean isValuesFieldsValid() throws HeadlessException {
      if (username.getText().trim().isEmpty()) {
         JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("UsersWindow.username_mandatory.msg"),
                 TerminalUtil.getMessage("UsersWindow.username_invalid.msg"), JOptionPane.ERROR_MESSAGE);
         return false;
      }
      if (password.getPassword().length == 0) {
         JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("UsersWindow.pswd_mandatory.msg"),
                 TerminalUtil.getMessage("UsersWindow.pswd_invalid.msg"), JOptionPane.ERROR_MESSAGE);
         return false;
      }
      if (! Arrays.equals(password.getPassword(), passwordConfirm.getPassword())) {
         JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("UsersWindow.pswd_must_match.msg"),
                 TerminalUtil.getMessage("UsersWindow.pswd_invalid.msg"), JOptionPane.ERROR_MESSAGE);
         return false;
      }
      if (chkExpiration.isSelected()) {
         if (! expiration.isEditValid()) {
            JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("UsersWindow.date_expiration_invalid.msg"),
                    TerminalUtil.getMessage("UsersWindow.date_invalid.msg"), JOptionPane.ERROR_MESSAGE);
            return false;
         }
         if (Calendar.getInstance().getTime().compareTo(expiration.getDate()) >= 0) {
            JOptionPane.showMessageDialog(this, TerminalUtil.getMessage("UsersWindow.expiration_in_past.msg"),
                    TerminalUtil.getMessage("UsersWindow.date_invalid.msg"), JOptionPane.ERROR_MESSAGE);
            return false;
         }
      }
      return true;
   }

   private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
      if (!usersList.isSelectionEmpty()) {
         ((TerminalUserListModel) usersList.getModel()).removeUser(usersList.getSelectedIndex());
         btnSaveUsersList.setEnabled(! server.isReadOnly());
         clearFields();
      }
   }//GEN-LAST:event_btnRemoveUserActionPerformed

   private void btnSaveUsersListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUsersListActionPerformed
      if (JOptionPane.showConfirmDialog(this, TerminalUtil.getMessage("UsersWindow.confirm_save_changes.msg"),
              TerminalUtil.getMessage("UsersWindow.save_users.msg"), JOptionPane.YES_NO_OPTION,
              JOptionPane.QUESTION_MESSAGE) == 0) {
         saveUsers();
      }
   }//GEN-LAST:event_btnSaveUsersListActionPerformed

   private void saveUsers() {
      final TerminalUserListModel model = (TerminalUserListModel)usersList.getModel();
      try {
         usersRepository.clearUsers();
         for (TerminalUser user : model.getUsers()) {
            usersRepository.addUser(user);
         }
         usersRepository.save();
      } catch (AuthenticatorException ex) {
         JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                 TerminalUtil.getMessage("UsersWindow.error_saving.msg"), JOptionPane.ERROR_MESSAGE);
         LOG.error("Error saving users to file.", ex);
      } finally {
         btnSaveUsersList.setEnabled(false);
      }
   }

   private void usersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_usersListValueChanged
      if (! evt.getValueIsAdjusting()) {
         if (usersList.getSelectedIndex() >= 0) {
            final TerminalUser user = ((TerminalUserListModel)usersList.getModel()).getUserAt(usersList.getSelectedIndex());
            if (user != null) {
               String pswd;
               try {
                  pswd = authenticator.decrypt(user.getPassword());
               } catch (AuthenticatorException ex) {
                  JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(),
                          TerminalUtil.getMessage("UsersWindow.error_get_pswd.msg"), JOptionPane.ERROR_MESSAGE);
                  LOG.error("Error decrypting password.", ex);
                  pswd = "";
               }
               username.setText(user.getUsername());
               password.setText(pswd);
               passwordConfirm.setText(pswd);
               chkExpiration.setSelected(user.getExpiration() != null);
               expiration.setEnabled(chkExpiration.isSelected() && ! server.isReadOnly());
               expiration.setDate(user.getExpiration());
               btnRemoveUser.setEnabled(! server.isReadOnly());
               btnConfirmUser.setEnabled(false);
            }
         } else {
            btnRemoveUser.setEnabled(false);
         }
      }
   }//GEN-LAST:event_usersListValueChanged

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnClose;
   private javax.swing.JButton btnClearUser;
   private javax.swing.JButton btnConfirmUser;
   private javax.swing.JButton btnRemoveUser;
   private javax.swing.JButton btnSaveUsersList;
   private javax.swing.JCheckBox chkExpiration;
   private org.jdesktop.swingx.JXDatePicker expiration;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JToolBar.Separator jSeparator1;
   private javax.swing.JToolBar.Separator jSeparator2;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private javax.swing.JToolBar jToolBar3;
   private javax.swing.JPasswordField password;
   private javax.swing.JPasswordField passwordConfirm;
   private javax.swing.JLabel pswdConfirmLabel;
   private javax.swing.JLabel pswdLabel;
   private javax.swing.JPanel userDetailsPanel;
   private javax.swing.JTextField username;
   private javax.swing.JLabel usernameLabel;
   private javax.swing.JList<String> usersList;
   private javax.swing.JPanel usersPanel;
   // End of variables declaration//GEN-END:variables

   private void configureComponents() {
      final DocumentListener listener = new FieldsChangeListener();
      username.getDocument().addDocumentListener(listener);
      password.getDocument().addDocumentListener(listener);
      passwordConfirm.getDocument().addDocumentListener(listener);
      expiration.getEditor().getDocument().addDocumentListener(listener);
      authenticator = server.getUserAuthenticator();
      usersRepository = server.getUserRepository();
      usersList.setModel(new TerminalUserListModel(usersRepository));
      username.setEnabled(! server.isReadOnly());
      password.setEnabled(! server.isReadOnly());
      passwordConfirm.setEnabled(! server.isReadOnly());
      expiration.setEnabled(! server.isReadOnly());
      btnConfirmUser.setEnabled(! server.isReadOnly());
      btnRemoveUser.setEnabled(! server.isReadOnly());
      btnClearUser.setEnabled(! server.isReadOnly());
      btnSaveUsersList.setEnabled(! server.isReadOnly());
      chkExpiration.setEnabled(! server.isReadOnly());
   }

   private void exit() {
      setVisible(false);
      dispose();
   }

   private void clearFields() {
      username.setText("");
      password.setText("");
      passwordConfirm.setText("");
      chkExpiration.setSelected(false);
      expiration.setDate(null);
   }

   private class FieldsChangeListener implements DocumentListener {

      @Override
      public void insertUpdate(DocumentEvent e) {
         btnConfirmUser.setEnabled(! server.isReadOnly());
      }

      @Override
      public void removeUpdate(DocumentEvent e) {
          btnConfirmUser.setEnabled(! server.isReadOnly());
      }

      @Override
      public void changedUpdate(DocumentEvent e) {
         btnConfirmUser.setEnabled(! server.isReadOnly());
      }
   }

   private class TerminalUserListModel extends AbstractListModel<String> {

      private final List<TerminalUser> users;

      public TerminalUserListModel(UserRepository repository) {
         final Collection<TerminalUser> terminalUsers = repository.getUsers();
         users = new ArrayList<>(terminalUsers.size());
         for (TerminalUser u : terminalUsers) {
            users.add(u);
         }
         terminalUsers.forEach(users::add);
         Collections.sort(users, (o1, o2) -> o1.getUsername().compareTo(o2.getUsername()));
      }

      @Override
      public int getSize() {
         return users.size();
      }

      @Override
      public String getElementAt(int index) {
         return users.get(index).getUsername();
      }

      public TerminalUser getUserAt(int index) {
         return users.get(index);
      }

      public int indexOfUsername(final String username) {
         for (int i = 0; i < users.size(); i++) {
            if (users.get(i).getUsername().equalsIgnoreCase(username)) {
               return i;
            }
         }
         return -1;
      }

      public TerminalUser findUser(final String username) {
         final int index = indexOfUsername(username);
         if (index >= 0) {
            return users.get(index);
         }
         return null;
      }

      public boolean addUser(final TerminalUser user) {
         if (indexOfUsername(user.getUsername()) < 0) {
            users.add(user);
            fireIntervalAdded(this, users.size() - 1, users.size() - 1);
            return true;
         }
         return false;
      }

      public TerminalUser removeUser(int index) {
         TerminalUser user = users.remove(index);
         fireIntervalRemoved(this, index, index);
         return user;
      }

      public void clearUsers() {
         int endIndex = users.size() - 1;
         users.clear();
         fireIntervalRemoved(this, 0, endIndex);
      }

      public List<TerminalUser> getUsers() {
         return users;
      }
   }
}
