/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.rgt.gui;

import java.awt.Dimension;
import java.awt.Insets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.rgt.CancelableExecutor;
import org.rgt.ServerStatus;
import org.rgt.Session;
import org.rgt.TerminalException;
import org.rgt.TerminalServer;
import org.rgt.TerminalServerListener;
import org.rgt.TerminalUtil;
import org.rgt.TextScreen;

/**
 *
 * @author fabio_uggeri
 */
public class ViewSessionWindow extends javax.swing.JDialog implements TerminalServerListener {

   private static final Integer[] FONT_SIZE_OPTIONS = new Integer[]{8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36};

   private static final int[] REFRESH_INTERVALS = new int[]{0, 1, 3, 5, 10};

   private static final Map<Session, ViewSessionWindow> sessionsInView = Collections.synchronizedMap(new HashMap<>());

   private final CancelableExecutor executor;

   private final TerminalServer server;

   private final Session session;

   private transient UpdateScreenTask screenUpdater = null;

   /**
    * Creates new form ViewSessionsWindow
    *
    * @param parent
    * @param server
    * @param session
    */
   private ViewSessionWindow(javax.swing.JDialog parent, final TerminalServer server, final Session session, final CancelableExecutor executor) {
      super(parent, false);
      this.server = server;
      this.session = session;
      this.executor = executor;
      initComponents();
      configureComponents();
   }

   public static void viewSession(final TerminalServer server, final Session session, final CancelableExecutor executor) {
      ViewSessionWindow win = sessionsInView.get(session);
      if (win == null) {
         win = new ViewSessionWindow(null, server, session, executor);
         sessionsInView.put(session, win);
         server.addListener(win);
         TerminalUtil.centralize(null, win);
         win.setTitle(session.getId() + " - " + session.getTerminalAddress() + " - " + session.getOSUser() + " - " + session.getAppPid());
         win.resizeWindow();
         win.setVisible(true);
      } else {
         win.toFront();
         win.repaint();
      }
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of
    * this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      topPanel = new javax.swing.JPanel();
      jToolBar1 = new javax.swing.JToolBar();
      btnRefresh = new javax.swing.JButton();
      comboInterval = new javax.swing.JComboBox<>();
      jSeparator1 = new javax.swing.JToolBar.Separator();
      fontSize = new javax.swing.JComboBox<>();
      jToolBar2 = new javax.swing.JToolBar();
      btnClose = new javax.swing.JButton();
      terminalScreen = new org.swingutils.console.Console();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setIconImage(new javax.swing.ImageIcon(getClass().getResource("/prompt.png")).getImage());
      setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowClosed(java.awt.event.WindowEvent evt) {
            formWindowClosed(evt);
         }
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar1.setRollover(true);

      btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/refresh.png"))); // NOI18N
      java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/rgt/gui/Bundle"); // NOI18N
      btnRefresh.setToolTipText(bundle.getString("ViewSessionWindow.btnRefresh.toolTipText")); // NOI18N
      btnRefresh.setFocusable(false);
      btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnRefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnRefresh.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRefreshActionPerformed(evt);
         }
      });
      jToolBar1.add(btnRefresh);

      comboInterval.setToolTipText(bundle.getString("ViewSessionWindow.refreshInterval.toolTipText")); // NOI18N
      comboInterval.setFocusable(false);
      comboInterval.setRequestFocusEnabled(false);
      comboInterval.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboIntervalActionPerformed(evt);
         }
      });
      jToolBar1.add(comboInterval);
      jToolBar1.add(jSeparator1);

      fontSize.setToolTipText(bundle.getString("ViewSessionWindow.fontSize.toolTipText")); // NOI18N
      fontSize.setFocusable(false);
      fontSize.setRequestFocusEnabled(false);
      fontSize.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            fontSizeActionPerformed(evt);
         }
      });
      jToolBar1.add(fontSize);

      jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
      jToolBar2.setRollover(true);

      btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
      btnClose.setToolTipText(bundle.getString("SessionsWindow.btnClose.toolTipText")); // NOI18N
      btnClose.setFocusable(false);
      btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
      btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
      btnClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCloseActionPerformed(evt);
         }
      });
      jToolBar2.add(btnClose);

      javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
      topPanel.setLayout(topPanelLayout);
      topPanelLayout.setHorizontalGroup(
         topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(topPanelLayout.createSequentialGroup()
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
            .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );
      topPanelLayout.setVerticalGroup(
         topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout terminalScreenLayout = new javax.swing.GroupLayout(terminalScreen);
      terminalScreen.setLayout(terminalScreenLayout);
      terminalScreenLayout.setHorizontalGroup(
         terminalScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 0, Short.MAX_VALUE)
      );
      terminalScreenLayout.setVerticalGroup(
         terminalScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 324, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(terminalScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, 0)
            .addComponent(terminalScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      exit();
      server.removeListener(this);      
   }//GEN-LAST:event_formWindowClosed

   private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
      executor.execute(this::updateScreen);
   }//GEN-LAST:event_btnRefreshActionPerformed

   private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
      exit();
   }//GEN-LAST:event_btnCloseActionPerformed

   private void fontSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSizeActionPerformed
      terminalScreen.setFontSize((int) fontSize.getSelectedItem());
      resizeWindow();
   }//GEN-LAST:event_fontSizeActionPerformed

   private void comboIntervalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIntervalActionPerformed
      createTimer();
   }//GEN-LAST:event_comboIntervalActionPerformed

   private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      executor.execute(this::updateScreen);
   }//GEN-LAST:event_formWindowOpened

   private void createTimer() {
      int selectedInterval;
      cancelTimer();
      selectedInterval = comboInterval.getSelectedIndex();
      if (selectedInterval > 0 && selectedInterval < REFRESH_INTERVALS.length) {
         final int interval = REFRESH_INTERVALS[selectedInterval] * 1000;
         screenUpdater = new UpdateScreenTask(interval, "Monitoring Session: " + session);
         screenUpdater.start();
      }
      btnRefresh.setEnabled(selectedInterval <= 0);
   }

   private void cancelTimer() {
      if (screenUpdater != null) {
         screenUpdater.cancel();
         screenUpdater = null;
      }
      btnRefresh.setEnabled(true);
   }

   private void resizeWindow() {
      final Insets insets = getInsets();
      final int width = insets.left + insets.right + terminalScreen.getPreferredSize().width;
      final int height = insets.top + insets.bottom + topPanel.getPreferredSize().height + terminalScreen.getPreferredSize().height;
      setSize(new Dimension(width, height));
   }

   private void exit() {
      if (sessionsInView.containsKey(session)) {
         sessionsInView.remove(session);
         cancelTimer();
         executor.clear();
         java.awt.EventQueue.invokeLater(() -> setVisible(false));
      }
   }

   @Override
   public void notification(TerminalServer server, String message) {
      // do nothing
   }

   @Override
   public void configurationLoaded(TerminalServer server) {
      // do nothing
   }

   @Override
   public void configurationSaved(TerminalServer server) {
      // do nothing
   }

   @Override
   public void stateUpdate(TerminalServer server) {
      // do nothing
   }

   @Override
   public void statusChanged(TerminalServer server, ServerStatus previousStatus) {
      // do nothing
   }

   @Override
   public void sessionOpen(Session session) {
      // do nothing
   }

   @Override
   public void sessionClose(Session session) {
      exit();
   }

   @Override
   public void serviceStart(TerminalServer server) {
      // do nothing
   }

   @Override
   public void serviceStop(TerminalServer server) {
      exit();
   }

   private void configureComponents() {
      setIntervalOptions();
      fontSize.setModel(new DefaultComboBoxModel<>(FONT_SIZE_OPTIONS));
      fontSize.setSelectedIndex(2);
   }

   private void setIntervalOptions() {
      comboInterval.addItem(TerminalUtil.getMessage("ViewSessionWindow.interval.manualOption"));
      /* First entry is manual option */
      for (int i = 1; i < REFRESH_INTERVALS.length; i++) {
         comboInterval.addItem(TerminalUtil.getMessage("ViewSessionWindow.interval.secondsOption", REFRESH_INTERVALS[i]));
      }
   }

   private void updateScreen() {
      try {
         final TextScreen screen = server.getTerminalScreen(session.getId());
         if (screen == null) {
            cancelTimer();
            return;
         }
         if (terminalScreen.getColumns() != screen.getColumns() || terminalScreen.getRows() != screen.getRows()) {
            terminalScreen.setRowsColumns(screen.getRows(), screen.getColumns());
            resizeWindow();
         }
         for (int r = 0; r < screen.getRows(); r++) {
            for (int c = 0; c < screen.getColumns(); c++) {
               terminalScreen.print(r, c, screen.getChar(r, c), screen.getFGColor(r, c), screen.getBGColor(r, c));
            }
         }
         terminalScreen.repaint();
      } catch (TerminalException ex) {
         JOptionPane.showMessageDialog(this,
                 TerminalUtil.getMessage("ViewSessionsWindow.update_eror.msg") + ":\n" + ex.getMessage(),
                 TerminalUtil.getMessage("ViewSessionsWindow.update_eror.title"),
                 JOptionPane.ERROR_MESSAGE);
         exit();
      }
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnClose;
   private javax.swing.JButton btnRefresh;
   private javax.swing.JComboBox<String> comboInterval;
   private javax.swing.JComboBox<Integer> fontSize;
   private javax.swing.JToolBar.Separator jSeparator1;
   private javax.swing.JToolBar jToolBar1;
   private javax.swing.JToolBar jToolBar2;
   private org.swingutils.console.Console terminalScreen;
   private javax.swing.JPanel topPanel;
   // End of variables declaration//GEN-END:variables

   private class UpdateScreenTask extends Thread {

      private final int interval;

      private boolean running = false;

      public UpdateScreenTask(final int interval, final String name) {
         super(name);
         this.interval = interval;
      }

      @Override
      public void run() {
         running = true;
         do {
            try {
               updateScreen();
               sleep(interval);
            } catch (InterruptedException ex) {
               running = false;
            }
         } while (running);
      }

      public void cancel() {
         running = false;
         interrupt();
      }
   }
}
