#RGT Options
#Wed Nov 17 18:42:44 BRT 2021

#########################
# Server configurations #
#########################
server.address=
server.port=7654
server.appPort=7655
server.adminPort=7656
server.logPathName=rgt-server.log
server.logLevel=INFO
server.sessionsCheckInterval=10s
server.sessionIdleTimeout=0m
server.maxWaitingLoginApps=5
#server.profile.port=6060

#################################
# Standalone App configurations #
#################################
standalone.enabled=false
standalone.authentication.mode=ldap
standalone.authentication.ldap.address=ldap-server.domain.net
standalone.authentication.ldap.query.user=cn=anonymous
standalone.authentication.ldap.query.pswd=
standalone.authentication.ldap.users.base=cn=users,dc=domain,dc=net
standalone.authentication.ldap.user.groups.attribute=groupmembership
standalone.authentication.ldap.user.status.attribute=ldap_user_status_attr
standalone.authentication.ldap.user.status.active=100
standalone.authentication.ldap.user.name.attribute=uid
standalone.authentication.ldap.user.type.attribute=objectclass
standalone.authentication.ldap.user.type=ldap_user_type_attr
standalone.authentication.ldap.account.status.attribute=accountstatus
standalone.authentication.ldap.account.status.active=ACTIVE
standalone.authentication.ldap.groups.base=cn=software,cn=groups,dc=domain,dc=net
standalone.authentication.ldap.groups=cn\=group1,cn\=functions,cn\=groups,dc\=domain,dc\=net;cn\=group2,cn\=software,cn\=groups,dc\=domain,dc\=net

###########################
# Terminal configurations #
###########################
terminal.authentication.mode=passthrought
terminal.logLevel=ERROR
terminal.logPathName=%USERPROFILE%\\rgt-terminal.log
#terminal.TCPReadBufferSize=32768
#terminal.TCPWriteBufferSize= 32768

######################
# App configurations #
######################
application.logLevel=ERROR
application.logPathName=logs-app\\rgt-app-${date}-${time}-${pid}.log
application.communicationLackTimeout=0m
application.console.show=false
application.logDaysRetention=7
application.launchTimeout = 30s
application.loginTimeout = 30s
application.minLaunchInterval = 500ms

#################################
# Runtime environment variables #
#################################
env.oci64_path=C\:\\oracle\\instantclient_x64_12_2
env.oci32_path=C\:\\oracle\\instantclient_x86_12_2
#env.RGT_THREAD_TYPE=cfl
#env.RGT_LOG_LEVEL=TRACE
#env.RGT_LOG_PATH_NAME=c:\\temp\\rgt-app.log
#env.RGT_UPDATE_MODE=MAIN_THREAD

############################################
# LDAP configuration for admin connections #
############################################
admin.authentication.mode=passthrought
#admin.authentication.mode=ldap
admin.authentication.ldap.address=ldap-server.docmain.net
admin.authentication.ldap.query.user=cn=anonymous
admin.authentication.ldap.query.pswd=
admin.authentication.ldap.users.base=cn=users,dc=domain,dc=net
admin.authentication.ldap.user.groups.attribute=groupmembership
admin.authentication.ldap.user.status.attribute=ldap_user_status_attr
admin.authentication.ldap.user.status.active=100
admin.authentication.ldap.user.name.attribute=uid
admin.authentication.ldap.user.type.attribute=objectclass
admin.authentication.ldap.user.type=ldap_user_status_attr
admin.authentication.ldap.account.status.attribute=accountstatus
admin.authentication.ldap.account.status.active=ACTIVE
admin.authentication.ldap.groups.base=cn=software,cn=groups,dc=domain,dc=net
admin.authentication.ldap.groups=uid\=group,cn\=app,cn\=users,dc\=domain,dc\=net;cn\=group,cn\=functions,cn\=groups,dc\=domain,dc\=net;cn\=group,cn\=email,cn\=groups,dc\=domain,dc\=net
admin.fileTransferChunkSize=262144
admin.TCPReadBufferSize=131072
admin.TCPWriteBufferSize=131072

############################################
# Server health check configuration        #
############################################
server.health.enabled = false
server.health.checkInterval = 5s
server.health.cpuThreshold = 90
server.health.cpuResumeThreshold = 80
server.health.maxCpuAlerts = 60
server.health.memoryThreshold = 90
server.health.memoryResumeThreshold = 80
server.health.maxMemoryAlerts = 60
server.health.diskThreshold = 95
server.health.diskResumeThreshold = 90
server.health.maxDiskAlerts = 60
server.health.pendingLoginTimeout = 1m0s
server.health.maxPendingLogins = 10
server.health.maxPendingLoginsAlerts = 5
server.health.maxTotalAlerts = 10
